### ISSUE TITLE
Translations or koi navigation error

### ISSUE THREAD

**Issue by haydn** [katalyst/koi#130]
I'm get this error when using `koi_render_navigation` in 97b4cd9d965e818828593ac58b5e582cd3577a04:

```
undefined method `attr_accessible' for #<Class:0x007fc9b7d75748>
```

Looks like it's something to do with translations/settings.

Workaround for now was to drop back to 1984931dc980296082fd58c17b24a74fbaaab640.

**Comment by dbaines** [comment]
Marking this as done as it's 2 years old and no ones run in to the problem since.
