### ISSUE TITLE
DEPRECATION WARNING: `serialized_attributes`

### ISSUE THREAD

**Issue by rahult** [katalyst/koi#151]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from ___sers_rahult__evelopment_katalyst_rails_gems_koi_app_views_koi_admin_crud__form_field_collection_errors_html_erb___3886463269190009819_70230119352700 at /Users/rahult/Development/katalyst/rails/gems/koi/app/views/koi/admin_crud/_form_field_collection_errors.html.erb:5

**Comment by dbaines** [comment]
One of the things that will be fixed in the Rails 5 upgrade
