### ISSUE TITLE
scoped_search is broken

### ISSUE THREAD

**Issue by rahult** [katalyst/koi#152]
scoped_search is not working with inherited_resource so I have disabled it.

We need to make choice on whether to fix it or replace it with something new.

Also it does not work with STI anymore.

User in asset manager search, if we try to use scoped_search we get the list of all assets back instead of the type defined.

https://github.com/wvanbergen/scoped_search/issues/112

**Comment by dbaines** [comment]
@Obversity @pvawser01 Can you guys take a quick look at this issue. It may have been resolved or may have been an issue with 1.0. 
I'm looking at the asset manager now and the images and documents seem to be returning the correct things, so I'm guessing it's fixed? Thanks!

**Comment by dbaines** [comment]
Considering this fixed.
