### ISSUE TITLE
simple_form custom wrapper 

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#159]
- Start Date: 2017-02-09
- Owner: DB

# Summary

Update all Koi form fields with a `:koi` wrapper to prevent application form changes bleeding through to Koi.

# Motivation

When you change the `simple_form` initialiser in your app, it bleeds through to Koi. Not a huge issue but it can be confusing and depending on the change could result in some weird things happening in the admin. 

# Detailed design

1. Update the default `simple_form.rb` initializer to include a `:koi` wrapper type. 
1. Go through koi and update each and every form field to use `wrapper: :koi`
1. Profit 🎸

# Drawbacks

Long process. 
When upgrading from an older Koi, the developer will need to be on the lookout for any custom form fields and be aware to update their wrapper. 

# Alternatives

Alternatively we could keep Koi using the default `:boostrap` form field wrapper and instead start using a different one on the front-end. This could even be an intentional change in ornament to fix this moving forward. 

# Unresolved questions

Are we happy with the way Koi forms look?   
Should we talk about that before we make this change?

**Comment by jsidoryn** [comment]
seems sensible to add a :koi wrapper rather than :bootstrap. discussion around the way forms looks will likely be addressed elsewhere.
