### ISSUE TITLE
Sitemap - Target dropdown

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#163]
- Start Date: 2017-02-09
- Owner: DB

# Summary

Add a `target` drop-down field for navitems to control opening navitem links in new windows or same window.

# Motivation

Sometimes we need to open navitems in new windows. Maybe they link to an external website or maybe it's a document or something. 

Ornament has bandaided this a little bit with it's external link JS stuff, but it would be nice to do it properly. 

# Detailed design

When creating or modifying a navitem in the sitemap the user is presented all the usual options such as title and URL etc. but is also given the option to change the `target` of the link. 

The target drop-down will control if the link opens in a new window (eg. exactly the same as the `target` html attribute on a link)

# Drawbacks

Possible confusion or noise to user when creating navitems. 

# Alternatives

The current alternative is a javascript approach. 

# Unresolved questions

Adding target is cool, is there anything else we may want to consider adding while we're here?

**Comment by rahult** [comment]
I like it, definitely can do. Should be not that hard. Any advantage to use target dropdown instead of boolean? I don't see how, just curious.

**Comment by dbaines** [comment]
Target dropdown makes a lot of sense :)
