### ISSUE TITLE
Ability to add more menus to Koi header

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#164]
Similar to Koi::Menu.advanced = { ... }

Helpful for sites with multiple subsites. We could have menus for each subsite that contains modules just for that subsite. 

A good example is YSA that has the Hubs subsite. We could have something like:

Koi::Menu.hubs = { ... }

**Comment by rahult** [comment]
Sweet, this is only list as well. Also can we expand this to have nested menus in the first level.

**Comment by dbaines** [comment]
Sure nested menus sounds like a good idea too

**Comment by dbaines** [comment]
Implemented a while back.
