### ISSUE TITLE
Auto-populate module items in sitemap under a module NavItem (optional)

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#169]
Can be done now with god settings but would be nice if it was a boolean setting against the NavItem. 

It would autopopulate all module items and if items have nested modules, populate those too. 

This wouldn't reflect in the Sitemap (eg. those module items won't appear in the sitemap page and be orderable) but would output via render_koi_navigation. Their order would be defined by the model itself.

**Comment by rahult** [comment]
Hmm, this one might be tricky. Lets discuss this offline first.

**Comment by dbaines** [comment]
Closing in favour of other suggestions/RFCs
