### ISSUE TITLE
Editing settings

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#177]
- Start Date: 2017-02-13
- Owner: DB

# Summary

Editing settings on the "extra" tab in modules is crashing with `Undefined method "is_nested?"`

# Steps to reproduce

1. Go to a module index listing 
1. Click on the "extra" tab  
1. Click on "edit" next to one of the settings  

# Expected results

The edit form for the setting should be available for editing 

# Actual results

The website fails silently since the form shows in a modal which is ajaxed in. So the ajax call results in a 500 error so the modal never shows. 

# Additional notes

Seems related to `images` field.

`translation.rb` has a FIXME next to has_many :images so maybe it was a known issue or a bandaid fix or something:

```ruby
  # FIXME: Refactored from has
  has_many :images
```

Koi 3.0 might be drastically changing settings anyway.

**Comment by dbaines** [comment]
From my testing seems to be related to the `:images` field for settings. Once I remove this from `setting.rb`'s form fields the form loads and saves correctly. 
The lightbox that it shows in is broken too though so the form appears at the bottom of the page. I can fix that, but I guess we need to determine if we need `images` for settings and what it will impact if we remove it.

**Comment by dbaines** [comment]
Started a hotfix branch: https://github.com/katalyst/koi/commits/hotfix/177-EditingSettings
I've fixed the add/edit settings using the old Koi 1 modal code so it now looks inline with the rest of Koi. Still crashes due to `images` though.

**Comment by dbaines** [comment]
I've gotten further by changing:

```ruby
has_many :images
```

to:

```ruby
has_many :images, as: :attributable
accepts_nested_attributes_for :images, allow_destroy: true
```

Then setting `images: { type: :inline }` to get the form field to show up without crashing! Yay!
But now the Javascript for inline nested fields doesn't work because the JS is rendered through a yield 😭  (which obviously doesn't render since the partial is being injected via ajax)

The inline nested JS is compiled in the `koi.js` in the redesign branch, so now we need to decide whether it's worth fixing this in master or if it's worth holding off on fixing this until the redesign lands.

**Comment by dbaines** [comment]
This issue is now fixed in redesign branch. 
Could be problematic to back-port.

**Comment by Obversity** [comment]
@dbaines 

Back porting should be doable as long as we don't worry about image settings, yeah? I actually can't think of any of our recent sites that use image settings. To be honest, I'm not sure I even know  how to create one, lol.

**Comment by dbaines** [comment]
@Obversity This is true. As long as we don't have any settings that use images it should be fine.

**Comment by Obversity** [comment]
And even then, having it mostly-functioning would be much better than not-functioning-at-all, so it'd still be a win.
