### ISSUE TITLE
dragonfly app: :image causing bug

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#188]
- Start Date: 2017-02-09
- Owner: TBA

# Summary

*Short description of the bug.*

# Steps to reproduce

If a dragonfly_accessor is given app: :image but the user accidentally uploads a file instead of an image, or visa versa, the it throws an exception when trying to generate the file icon / image thumbnail.

# Expected results

*What is the result you are expecting?*

# Actual results

*What was the actual result?*

# Additional notes

*Anything that didn’t fit into the above sections should be added here. This could be environment information or screen shots for example.*

**Comment by jsidoryn** [comment]
@Obversity test it

**Comment by pvawser01** [comment]
I have run some tests with a fresh application created from KOI HEAD branch. This seems impossible if the generators are used. The generators are adding the appropriate accessor type and validations for file types. The only way I see that the error explained could happen is if a developer implements an image attribute manually and does not define it correctly. 
I am setting this as closed.
