### ISSUE TITLE
Add sitemap.xml generation to koi

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#191]
- Start Date: 2017-02-10
- Owner: BP
- RFC PR: (leave this empty)

# Summary

Currently generating a `sitemap.xml` file is a manual and potentially lengthy process depending on the complexity of the website.

# Motivation

Save time and money. 

# Detailed design

*Note: This assumes we use the same process as we currently are*

Start by adding these gems to Koi:

```
gem 'sitemap_generator'
gem 'whenever'
```

Add a schedule to generate it every day:

```
every 1.day, :at => '12:01 am' do
  rake "sitemap:refresh:no_ping"
end
```

And the deploy hook:

```
on_app_master do
  run "cd #{config.release_path}; bundle exec whenever --set environment=#{config.framework_env} --update-crontab '#{config.app}_#{config.framework_env}'"
end
```

Now we need to either expose a way for the application to determine what gets pushed to the sitemap. 

We will probably need a way to specify if we push just the collection route or the record routes as well. For example, `Page` we would want the records pushed to the sitemap, but a `BoardMember` index listing might not have a show page so we only want to push the collection/index page to the sitemap. 

We have two options here I think: 

1. We can either add a way in the model to say that it's `sitemappable` or something that pushes it to the sitemap. 

1. The other option is we can leave the full sitemap configuration to the application and maybe just have a couple of helpers that make life a bit easier, but the entire `sitemap.rb` file will live in the application and be hard-coded, eg:

```
# this stuff could be generated for us 
require 'rubygems'
require 'sitemap_generator'

SitemapGenerator::Sitemap.compress = false
SitemapGenerator::Sitemap.default_host = Prx::Application.config.action_mailer[:asset_host]

SitemapGenerator::Sitemap.create do
  Page.all.reject { |r| r.respond_to?(:hide?) && r.hide? && !r.slug.blank? }.each do |page|    add page_path(page), :changefreq => 'monthly', priority: 0.5  end
  add '/board-of-directors', changefreq: 'yearly',  priority: 0.3
end
```

# Drawbacks

There are concerns that `sitemap.xml` doesn't really add a whole lot to search engine visibility or optimisation. Sites that we haven't added it for are still doing fine in Google rankings. 

Even if we *do* have automated sitemap generation, we *still* need to go about adding the site to webmaster tools on google and submitting the sitemap. It will save us dev time but there's still admin time to set it up. I don't think there's a way to automate this part. 

# Alternatives

We could keep doing it the way we are doing it. Maybe we could just better document it to make the process easier or maybe just add some helpers or smart-defaults to make sitemap generation quicker and easier. 

# Unresolved questions

Some more app-like sites wouldn't benefit from it. How would this perform on those sites? Would having an empty (or bare-bones) sitemap.xml be worse than no sitemap.xml? 

The `asset_host` will need to be set in the project, which is a little awkward because sometimes the project is generated before the final URL is known. How do we manage this? Koi setting? Do we stop generating the sitemap if there's no asset_host defined?

**Comment by jsidoryn** [comment]
i don't know the detail about the value of it but i've always had the general idea that there should be a sitemap.xml for all sites. does anyone else have any views on this?

if we can build it in a way so there's very little effort per site then it would likely be a good addition.

**Comment by Obversity** [comment]
Autogenerating accurate sitemaps isn't really feasible, unless we want to allow admins to edit changefreq and priority for pages and other modules in Koi. 

Quick example: Let's say a client creates a "Core Services" page, which is very important to them. They feature it in the primary navigation. Let's say they then create a  page "<Very-specific and niche service>" for a very specific and niche service. This page isn't particularly important, but is still worth having on the site. 

The code that generates the sitemap.xml will loop over all pages and generate a `<url>` for each Page, with a `<changefreq>` and a `<priority>`. However, without any additional data, the sitemap-generating code has no way of knowing that it should give the "Core Services" page a very high priority (and possibly a very high change-frequency") , but give the niche page a low priority/frequency. 

In other words, if we want to do sitemaps properly, with an accurate changefreq and priority, we'd need settings (or fields on the model) to record a page's priority and frequency of change. 

RE the value of sitemap.xml:  The SEO crowd seems to be in two minds about it. On the one hand, it's one more thing they can advise their clients that they need to get sorted (which makes them sound professional, like they know what they're talking about). On the other hand, I'm yet to read a good explanation of how a sitemap.xml actually helps—which seems to be why the other half of the SEO crowd has decided that a sitemap.xml isn't really worth much. 

I suspect there are much higher value, less painful ways of boosting the SEO of our clients. The best advice I've read is to just make your site easily crawlable, make sure the good/important content is easily accessible via navigation, make sure your page titles are good (but not too long), and make sure there's other content on the web linking to it (inbound links). SSL helps. User generated content can apparently help (comments, maybe even upvotes, etc).
