### ISSUE TITLE
make SEO settings editable by regular admins and port global SEO rendering into global template

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#192]
- Start Date: 2017-02-10
- Owner: BP
- RFC PR: (leave this empty)

# Summary

the generated 'koi.rb' file doesn't specify the admin role for the SEO settings template, so by default it uses 'Super', meaning regular admins can't edit this stuff.

# Motivation

*Why are we doing this? What use cases does it support? What is the expected
outcome?*

# Detailed design

*This is the bulk of the RFC. Explain the design in enough detail for somebody
familiar with the framework to understand, and for somebody familiar with the
implementation to implement. This should get into specifics and corner-cases,
and include examples of how the feature is used. Any new terminology should be
defined here.*

# Drawbacks

*Why should we not do this? Please consider the impact on teaching Ember,
on the integration of this feature with other existing and planned features,
on the impact of the API churn on existing apps, etc.*

*There are tradeoffs to choosing any path, please attempt to identify them here.*

# Alternatives

*What other designs have been considered? What is the impact of not doing this?*

*This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.*

# Unresolved questions

*Optional, but suggested for first drafts. What parts of the design are still
TBD?*

**Comment by dbaines** [comment]
Pulling SEO stuff in to global template might be more of an Ornament thing. When you're done with the role stuff give me a nudge and I'll update Ornament :)

Ornament already has a lot of Koi-specific stuff in it (uploader requires asset controller, styleguide controller includes CommonControllerActions etc...) so I don't see this being a problem.

**Comment by dbaines** [comment]
What does everyone think about changing the keywords field to be a `string` rather than a `text`? Having a large textarea implies you can add line breaks and make it really long, when in reality the search engines that support keywords usually have a limit on keywords and definitely don't like line breaks in there. We could even add a text-limiter to further enforce the limitations on the field. 

The only benefit I can see of having a textarea is being able to read it a bit easier.

**Comment by jsidoryn** [comment]
Makes sense and I'm good with having it a string field. As you say, clients shouldn't be adding too many in.

**Comment by Obversity** [comment]
Makes sense to me, if that's what search engines prefer!
