### ISSUE TITLE
Inline Nested Script Load Ordering

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#211]
Problem:
Inline Nested partial uses `single_content_for`

This is problematic if using two inline_nested fields when the first is orderable and the second is not. The non-orderable script over-takes the orderable script resulting in the orderable nested field not being able to reorder. 

Fix:
Move the scripts out of inline_nested if possible, make the script a bit smarter to work with non-orderable and orderable nested fields at the same time. 
A possible pain point will be the cocoon callback but we might be able to proxy that through a document trigger.

**Comment by Obversity** [comment]
"A possible pain point will be the cocoon callback but we might be able to proxy that through a document trigger."

That sentence makes my brain hurt. 

I've come across this issue before, but wasn't brave enough to try for a fix at the time. Definitely worth looking at though. (Let me know if you think it's worth pairing on or if you're all good with it.)

**Comment by dbaines** [comment]
Fixed in redesign branch:
https://github.com/katalyst/koi/commit/23e923611b65ccf126a1a5fb765df63399800a04

Should be simple enough to back-port if needed
