### ISSUE TITLE
Crud.config options for datepickers

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#218]
- Start Date: 2016-07-12
- Owner: DB

# Summary

Make it super easy to customise the jQueryUI datepicker field in Koi

# Motivation

Sometimes we need multiple types of datepickers:
* You can only select future dates
* You can only select past dates
* Limited to the past two years

# Detailed design

Currenly all datepickers have the following settings: 

```
{
  dateFormat: 'dd/mm/yy',
  showButtonPanel: true,
  changeMonth: true,
  changeYear: true
}
```

Which is cool, but wouldn't it be cool if we could pass in options through crud config to set them on a per field basis in crud.config? 

```
custom_date_field: { type: :date, input_data: { change_month: false } }
```

👌

# Drawbacks

Literally nothing. 

# Alternatives

We could look in to alternative datepicker options while we're here. Are we happy with jquery ui's datepicker? I think it works well and gets the job done. 

# Unresolved questions

What number of options do we want? 
Syntax acceptable?

**Comment by jsidoryn** [comment]
@dbaines would you mind having a look at https://github.com/veracross/pickadate-rails and add your thoughts on it from a dev point of view. 

i like the interface a lot more on mobile but part of a broader discussion. just want to know if we should kill it off at the start if there's a problem with it.
