### ISSUE TITLE
Asset Manager - Confirm delete should be data-confirm

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#226]
- Start Date: 2016-07-012
- Owner: DB

# Summary

The confirm attribute when deleting something from the asset manager should be data-confirm rather than just confirm. 

This has been fixed in redesign branch but should probably be back-ported to older branches.

# Steps to reproduce

Try and delete an asset

# Expected results

It should ask you if you want to confirm the delete

# Actual results

It deletes the asset immediately 

# Additional notes

This is just a missed upgrade issue. Old rails use to have `confirm: "Are you sure?"` but now it needs to be `data: { confirm: "Are you sure?" }`

**Comment by jsidoryn** [comment]
@dbaines do you think it should still be ported back? if so, make it bug.

**Comment by jsidoryn** [comment]
@dbaines don't worry about it, i've made it a bug for now

**Comment by dbaines** [comment]
@jsidoryn pull request ready https://github.com/katalyst/koi/pull/266
