### ISSUE TITLE
Commits for Koi must be made by someone else

### ISSUE THREAD

**Issue by jsidoryn** [katalyst/koi#235]
- Start Date: (fill me in with today's date, 2017-02-08)

# Summary

Whenever a commit is made to Koi it must be done by someone other than the author. 

# Motivation

By having the commit against the person who reviewed it, it increases ownership of the issue and increases the responsibility of the person reviewing as the commit goes against them. 

# Detailed design

Not sure how best for this to work. Will need some suggestions. 

This originally came from Haydn who said they are using it at his new workplace and is finding it works well. I can ask him for more details if needed. 

# Drawbacks

Takes a bit longer and a person may not be available. 

# Alternatives

Normal pull request system. 

# Unresolved questions

How should this work in practice.

**Comment by Obversity** [comment]
It'd be good to flesh out the actual process for doing this. I can't comment on it without thinking about how the commit process would actually work and knowing how much hassle that would be.

I do like the idea of increasing ownership for features, though, and this could be a novel way of doing it.
