### ISSUE TITLE
Smarter Koi Generators

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#236]
- Start Date: 9/2/2017
- RFC PR:  #208 

# Summary

Smarter koi generators so we write less boilerplate. 

# Motivation

When using the koi generators, I always have a mental list of things I still need to do afterwards to get stuff to work. However, mental lists are error prone, and it takes time to actually do these things. Many of these things can and should be automated to save time and bugs. 

It's much easier to remove well-formatted but unnecessary code, than it is to write it over and over again. 

# Detailed design

Koi currently has three generators:

rails generate koi:mailer
rails generate koi:admin_controller
rails generate koi:controller

Missing from the koi:controller generator is a permitted_params (rails' Strong Params) method in the front-end controller. This can pretty easily be added. 

Missing from the admin_controller and mailer generators is any kind of default crud field type configuration. This can be added with some effort and guesswork, to account for common things like

- images and files
- belongs_to associations
- status fields commonly configured as rails enums
- booleans
- dates
- description fields

and any other config that can easily be guessed from the `field_name:data_type` key value pairs given to the generators.

### Example

```bash
rails generate koi:admin_controller Article article_type:integer category:integer featured:boolean title:text date:datetime summary:text thumbnail_uid:string feature_image_uid:string body:text newsletter_issuu_embed:text newsletter_pdf_uid:string
```

With smarter generators: 

![image](https://cloud.githubusercontent.com/assets/7999019/22770416/41723712-eee0-11e6-9370-37e53336497e.png)

Regular Koi 2.2 generators: 
![image](https://cloud.githubusercontent.com/assets/7999019/22770474/ba918b8e-eee0-11e6-92e2-bb09495ceb3b.png)

# Drawbacks

- The code needs careful testing so that it doesn't generate config that doesn't work or that produces syntax errors. Generating code with code can be tricky. 
- It may occasionally guess the field types wrong if we're not careful, meaning you may have to delete or modify several lines of config. 

# Alternatives

We keep writing boilerplate. Ain't nobody got time for that.

**Comment by jsidoryn** [comment]
Closed
