### ISSUE TITLE
WYSIWYG Improvements

### ISSUE THREAD

**Issue by kippo** [katalyst/koi#238]
- Start Date: 2017-02-09
- Owner: KB for now
- RFC PR: (leave this empty)

# Summary

Improve WYSIWYG

# Motivation

Current implementation of CK editor has the following issues:

- Custom HTML and CSS needs to created through source view and can easily be broken by a client. Related to blocks based content.
- Styling is not indicative of how it looks on the front end. Related to issue #233.
- Writing content in the editor is not pleasurable. Most likely just treated as a dumping ground for word docs.

# Detailed design

- Ability to switch into writing mode for the field removing distractions and increasing size of editor. 
- CSS styles pulled into WYSIWYG. This would not be necessary should we proceed with #233.  

# Drawbacks

Pulling CSS styles into WYSIWYG could be onerous and may fall out of sync with live site.

*There are tradeoffs to choosing any path, please attempt to identify them here.*

# Alternatives

*What other designs have been considered? What is the impact of not doing this?*

*This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.*

# Unresolved questions

*Optional, but suggested for first drafts. What parts of the design are still
TBD?*

**Comment by dbaines** [comment]
> CSS styles pulled into WYSIWYG

I just did a CKEditor upgrade pull request, while I was there I noticed there's now a .css file you can generate whose styles get pulled in to the editor.

This could be generated by Ornament, something like this:

```scss
@import "ornament/core"; 
@import "aspects/normal";
body {
  padding: $x-small-unit;
  @include aspect-normal; 
}
```

This would generate a CSS file that pulls in the core (settings, resets, typography styles etc.), the normal "wysiwyg" aspect and then apply the aspect to the body, with a little bit of padding since the `body` margins get reset to zero.

**Comment by dbaines** [comment]
Seems to work on the old CKEditor too, here I've done a quick version for YSA, could be patched in to projects as we need it pretty effortlessly. 

![wysiwyg](https://cloud.githubusercontent.com/assets/685024/23950127/d43c49f2-09d9-11e7-9132-ade20aa1a9bd.jpg)

**Comment by Obversity** [comment]
Awesome!

**Comment by dbaines** [comment]
@Obversity I suppose we could set up some nicer defaults in Koi, but as long as the CSS is in the project (which would be generated by Ornament) Koi will pick it up and run with it with no modifications to Koi required.

**Comment by dbaines** [comment]
@kippo Do you think it's worthwhile copying across the default Ornament typograpahy styles in to Koi?

If the website uses the latest Ornament it will get actual type styles from the website, but if it's not (and we haven't made a custom ckeditor css file) it will get the default Ornament ones, like this. http://ornament.katalyst.com.au/styleguide/sample_content

Or should we just roll with the CKEditor defaults?

**Comment by dbaines** [comment]
Actually, I just realised webfonts are going to be an issue. We'd need to pull webfonts in to Koi from the application. 

Ornament could move the webfont code in to a partial, like `app/views/layouts/_webfonts` or something, then Koi could pull it in if it's found, using the fancy new application helper `partial_with_wrapper`.

**Comment by kippo** [comment]
@dbaines I see no need to pull default Ornament styles in assuming CKEditors defaults are good.
