### ISSUE TITLE
Spreadsheet view editor

### ISSUE THREAD

**Issue by kippo** [katalyst/koi#239]
- Start Date: 2017-02-09
- Owner: KB for now
- RFC PR: (leave this empty)

# Summary

The ability to edit large amounts of entries through a single spreadsheet view.

# Motivation

Editing the price of 50 different products is onerous. I have to open each one individually, edit it then save it. 

# Detailed design

Create a spreadsheet style editor that allows me to edit multiple entries through a single view.

# Drawbacks

*Why should we not do this? Please consider the impact on teaching Ember,
on the integration of this feature with other existing and planned features,
on the impact of the API churn on existing apps, etc.*

*There are tradeoffs to choosing any path, please attempt to identify them here.*

# Alternatives

*What other designs have been considered? What is the impact of not doing this?*

*This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.*

# Unresolved questions

*Optional, but suggested for first drafts. What parts of the design are still
TBD?*

**Comment by pvawser01** [comment]
@kippo Rather than a spread sheet interface would an inline bulk update feature be an alternative. 
I see this as an editable index view, where you change the data on the records in the table and save all at once. May have issues with pagination, not sure.
Thoughts?

**Comment by jsidoryn** [comment]
@pvawser01 i think this is what kipp is suggesting. @kippo ?

re pagination i'm expecting that either unfocussing the field would trigger an ajax action.

**Comment by Obversity** [comment]
This needs much more in the detailed design section to be properly discussed. We can't talk pros and cons unless we all have a reasonably good idea of what's being suggested.
