### ISSUE TITLE
Remove the i18n-active_record gem

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#240]
- Start Date: 09/02/2017
- Owner: BP
- RFC PR: #286

# Summary

This gem slows down Koi and the front-end considerably. 

# Motivation

Slowness is bad for users and bad for servers, and this gem makes both the backend and the front-end forms slow. 

This is because for each simple_form field on the form (i.e. nearly all of them), rails has to look up translations for labels, placeholders, hint text, etc. But it doesn't make just one database query for these. It makes a dozen, and they're all expensive `where ... like ...` queries. 

Here's just the queries for an `email` fields on a contact form: 

![image](https://cloud.githubusercontent.com/assets/7999019/22772231/6a1b12be-eeeb-11e6-81f0-97b598c2f27f.png)

This problem is compounded by the fact that the translations table is also used by Koi's "settings" feature (via single table inheritance, I think), and when a model has settings enable, it seems like every instance of that object you create, will create a bunch of (mostly empty) SEO settings for the record in this translations table. Minda's `translations` table has 37637 rows currently. 

Two real-world cases of it being problematic:

1. Minda rang up the other day complaining that the "My Choices" form/page on their site was crashing. Looking at the server logs, this gem was making over 500 database queries on pageload. This was nearly crashing the server, and the page itself took several minutes to load, if it loaded at all. 

2. YourSAy called recently to tell us that Koi was feeling slow to the point of being unusable. Similarly, one of the problems was that many of YourSAy's back-end forms have 20+ fields, resulting in 100 or so database queries just by this gem. 

# Solution

We remove the gem and instead use the simple i18n backend provided by rails. 

`I18n.backend = I18n::Backend::Simple.new`

If this ever proves to be a bottleneck, we could look into other backends. There are several. 

# Drawbacks

We still need the `settings` table/model, so we'll need to ensure we keep this in the project even if we remove the gem. 

The upside of using an active record i18n backend is that you could build an interface on top of it for admins to manage labels etc. However, this has never been implemented, and until then, it makes sense to remove it

# Alternatives

We could instead separate the Settings model and the Translations table so that it doesn't grow to huge numbers, where making that many queries actually becomes a usability/server problem. Making 500 queries (where the results get cached) on page load is feasible (although obviously not still not good) when the table has 200 records in it. When there are 37637, it's not feasible.

**Comment by dbaines** [comment]
> We still need the `settings` table/model, so we'll need to ensure we keep this in the project even if we remove the gem.

This is the sticking point for me. I see the benefit of removing the gem but losing the translations table would be problematic. How hard would it be to remove the inheritance and build up a `settings` table to make it stand on its own? What affects would that have on the upgrade path?

**Comment by Obversity** [comment]
Agreed, we've never had a project that's needed serious mutli-language capabilities, and if we did, it'd be a one off—not something we'd want to build into koi by default, just because of how difficult it is to maintain sites like that. 

We won't lose the translations table. The migration to create the table will remain in the project, as will the settings and translation models. I'm 90% sure that removing it won't cause any issues, but it should be easy to find out!

**Comment by jsidoryn** [comment]
Sounds like it can be tested fairly easily to see if it works before going ahead. Decent win if it works. I'd suggest pushing on with this but time boxing it. I'm expecting that settings might have a separate RFC for Koi 3 but regardless of anything that happens in the future this fix sounds like it's needed.

**Comment by pvawser01** [comment]
I have created a branch and pull request for this issue. It seems to work. I tested it locally on the min_v2 upgrade project and we no longer see the translation queries. Would be good for someone else to try it and see if they can spot any problems. I may have overlooked some areas that may be affected.

**Comment by jsidoryn** [comment]
@pvawser01 Please merge: https://github.com/katalyst/koi/pull/286
