### ISSUE TITLE
Prefab module: Users

### ISSUE THREAD

**Issue by jsidoryn** [katalyst/koi#243]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR: #206 

# Summary

Optionally generating users when bootstrapping a Koi project.

# Motivation

Users are something we need in a good 50% of our projects. Devise is already in the project, so it makes for to have a generator to build a bunch of the stuff we always need for users, plus any other user/koi integrations we think would be worth while for all projects. 

# Detailed design

Devise has generators that will do a lot of the work for us.

```
 rails generate koi:admin_controller User first_name:string last_name:string
 rails generate devise User
 rails generate devise:views users
 rails generate devise:controllers users
```
We can build any user-related features on top of this generated code. What these features might be is up for discussion. 

Examples of additional features:
- registration / login analytics
- an easy-to-access mail-to link in the users index view in Koi
- optional oauth flags for the generator that allow facebook/twitter login (and maybe spit out basic instructions on configuring a facebook/twitter app for this purpose)
- an improved user 'show' page template in koi 

# Drawbacks

If we build user features that don't meet the requirements of the specific project, this could cause more pain than it solves. We'll have to be careful to not to go overboard with features. 

# Alternatives

We build users custom every time, as we've done to date.

**Comment by jsidoryn** [comment]
@dbaines just chatting with @Obversity and he's done some work on this too. could you get together and work out how best to proceed.

**Comment by jsidoryn** [comment]
@Obversity just chatted with @dbaines and he was referencing your branch so this is now yours.

**Comment by pvawser01** [comment]
I like the idea of a koi generator to set up login. That way you just opt in when you need it, rather than switches or questions that you may not need.

**Comment by Obversity** [comment]
Yeah, I think I actually prefer the idea of having a `koi:users` generator, rather than asking in the bootstrap. 

It means the devise instructions won't get lost in all of the bootstrap output. And I can remember a couple of examples of sites where we haven't needed users off the bat, but they've been added later, for donations, or favouriting, or orders or whatever.

**Comment by jsidoryn** [comment]
Yep, I'm in favour of generators too. I'm also thinking that as we're adding new features we should start documenting. So could you add a wiki page with options as part of the work for this. 

@Obversity from what I understand this is a pretty simple implementation in that it just runs the Devise generators etc and is based on previous work you've done. Do you want to expand this at all or simply get it committed into the project?

**Comment by Obversity** [comment]
The work I did was to put it in the koi bootstrap, not as as a generator. I'd need to do a bit of work to make it a generator. This is probably more of a Koi 3 thing though. Yes, it could be as simple as running the devise generators, but if we want to make a real feature of it, we should probably give it some more thought before rushing into it, I reckon.

**Comment by jsidoryn** [comment]
Cool, agree it's worth a bit more thought or else there's not that much benefit from generating other generators : P

 Is it worth closing this and making a new RFC for this for Koi 3 once you've designed this.

**Comment by Obversity** [comment]
Yup, it probably is worth closing.

**Comment by Obversity** [comment]
I've updated the RFC to focus on implementation as a generator rather than in the bootstrap process. 

It'd be good to get your thoughts @pvawser01 and @dbaines regarding what could make your life easier in projects where we have users. Is there anything that you find yourself doing every time and wishing you didn't have to? 

Are there any user-related features that we think could be useful for any project?

**Comment by dbaines** [comment]
@Obversity I can't really think of anything I find myself doing a lot for users in Koi.

**Comment by jsidoryn** [comment]
@Obversity the list looks good and agree that we shouldn't be trying to add in a bunch of features that we'll have to unwind on projects where they aren't needed or where changes need to be made. 

So I think the list of features you have can be applicable for any project. 

*registration / login analytics*  

This will likely tie in with work that Kipp is doing for the dashboard. The implementation will become clearer once that work is done. 

*an easy-to-access mail-to link in the users index view in Koi*  

yep. 

*optional oauth flags for the generator that allow facebook/twitter login (and maybe spit out basic instructions on configuring a facebook/twitter app for this purpose)*

yep

*an improved user 'show' page template in koi*

this is probably going to evolve over time but good to get in early. 

The only other thing that came to mind is that almost all sites that have users has some sort of way to email them. These can either be system emails or Campaign Monitor emails. I'm wondering if there's anything we can do to bootstrap in this functionality, or maybe we should look at it as part of those areas themselves.
