### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by jsidoryn** [katalyst/koi#244]
- Start Date: 2017-02-13
- Owner: DB
- RFC PR: #264 

# Summary

Basic redesign to improve UI behaviour on large and small devices. 

# Motivation

Menus and module nesting has always been a problem. We've tried to tackle it in the past with extra menus and internal scrollbars but it's never been able to account for infinitely nested and infinitely long module lists. 

Being able to use Koi on mobile would be great too. 

# Detailed design

* Slide-out navigation for Infinitely nested navigation 

![redesign-menu](https://cloud.githubusercontent.com/assets/685024/22873118/b74a40f8-f20d-11e6-9ecc-fceb1af6dba3.jpg)

* Themable CSS
* Fixing weird UI quirks such as using the browser back/forward button to navigate between in-page tabs. 
* Keyboard shortcuts to move around Koi quicker 
* Redesigned default show page
* Dirty form checker to prevent users from leaving the edit page before saving their changes 
* Getting asset manager out of the modal and make it its own page 

![redesign-asset-edit](https://cloud.githubusercontent.com/assets/685024/22873127/c6821212-f20d-11e6-96c1-6b42c1a6697d.jpg)

* Adding drag-and-drop uploader to asset manager 

![redesign-asset-new](https://cloud.githubusercontent.com/assets/685024/22873138/d3348ddc-f20d-11e6-9508-20fe57252c88.jpg)

* Improve UX of sitemap to expose keys and hidden states and improving touch functionality with drag and drop 
* Lockable sitemap 

![redesign-sitemap](https://cloud.githubusercontent.com/assets/685024/22873141/dad6255a-f20d-11e6-8722-3570ab0639bb.jpg)

Addresses several existing issues:

* 122 - Remove "Add to Page" in asset manager when not in CKEditor
* 125 - Fullscreen asset manager
* 160,176 - CKEditor issues
* 179 - Lockable sitemap 
* 183 - Map form field
* 202 - Pagination for asset manager
* 211 - Inline Nested script ordering
* 219 - Asset manager callbacks for editing after uploading 
* 224 - Merged search and tag filters in asset manager 
* 226 - Deleting an asset wouldn't ask for confirmation 
* 227 - Removed NavItem show for mobile 

# Drawbacks

The responsive UI has dropped support for IE8 and IE9 since it's primarily built in Flexbox. 
As we found out in #259 asset compilation between an engine (koi) and the application may not be possible. This affects Koi branding and we may need to look at an alternative such as just a seperate .css file outside of sass. 

# Alternatives

We have tried other alternatives such as multiple menus and scrollable menus and while they work as a bandaid fix but they always end up with limitations.

**Comment by Obversity** [comment]
@dbaines  Looks fantastic! Nice work. 

Question: How easy is it to add items to the top bar? I'm slightly worried that having everything in the slide-out menu just adds an extra click to everything you want to do in Koi. It'd be good to still have the most important things duplicated in both the top bar and the sidebar. 

Now that I think about it, maybe just the sitemap would do.

**Comment by dbaines** [comment]
@Obversity Super-easy! It's another configurable setting in `koi.rb`

I was thinking about adding yoursay-style menu-with-more functionality incase it gets too crazy up there.

**Comment by jsidoryn** [comment]
Looks great! We could spend time reviewing this more broadly but I think it's such a big win that we should just get it in.

**Comment by dbaines** [comment]
Alright I'll start working on cleaning this up and getting it pull-request-ready. 
The filters are still up in the air a little bit. What I'll do for that is pull the search functions back in to the main UI out of the filter popup and make filters it's own RFC once that's done.

**Comment by dbaines** [comment]
Merged in to master
