### ISSUE TITLE
Review of form field types

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#246]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR: 

# Summary

Some field types may need fixes, others may need improvements, and there may be field types out there used in other projects.

# Motivation

Koi's range of form field types are what allows us to be productive in writing the backend to capture data. Not having to build a date input from scratch, or a select2 association input, or a nested form, etc, saves the company a huge amount of time. 

That said, I know from working with koi long enough that there are occasional problems with several types, and that others could be made to work better. Similarly, there are probably field types we've created for specific projects / use cases that have proved invaluable, and could possibly be pulled into koi. 

# Detailed design

I'd like to set aside a few hours to go through Yoursay and Oliveri (and any other crud-heavy applications) and take a look at:

(a) what fields have been added, that do new or interesting things
(b) what fields have been overridden to fix issues

I'd also like to go through Koi's existing fields and make sure all of them work in nested forms. Inline forms for `has_many` associations where the `has_many` has no relevance to the world outside of its parent, is a pattern we've been using a lot in recent projects. Having all field types work inside here is pretty crucial to being able to quickly build complex crud forms. 

# Drawbacks

Adding new field types adds to the codebase we need to maintain, so that it becomes more time consuming when want to add generic options to all field types (like showjs options).

**Comment by jsidoryn** [comment]
This RFC has the potential to get very big very quickly. I'm sure almost everyone has an idea of additional form widgets or form UI patterns that would be good. 

@Obversity it would definitely be good to go through those projects and see what you find. 

After that let's chat about how we want to proceed with this. It may be best to just add ideas in the comments or to have a meeting around this. We'll decide after you've had your initial pass through.

**Comment by Obversity** [comment]
Sounds good! Any that I find in koi that really need fixing I'll fix. Any interesting ones I find in other projects I'll comment here to see what people's opinions are on pulling them into Koi. There might be several, there might be none!

**Comment by jsidoryn** [comment]
Sounds good.

**Comment by Obversity** [comment]
Here's a field from YourSAy that looks handy. 

```ruby
# model
{ type: :has_one_inline }

# _form_field_has_one_inline.html.erb
<%= f.simple_fields_for attr do |ff| %>
  <%= render "form_fields", f: ff %>
<% end %>
```

This renders the form for the `:thing` inside the parent model form. 

Our `:inline` field type is great for `has_many :things` relationships, but we don't have an equivalent component for `has_one :thing` relationships. This neatly solves that problem. 

Any suggestions on what we call it in Koi? 

It'd make it much easier to break larger forms into smaller objects in koi where appropriate. For example, in Fund My Community, the application form has these fields: 

```
sponsor_name
sponsor_abn
sponsor_is_gst_registered
sponsor_inc_number
sponsor_inc_date
sponsor_contact_title
sponsor_contact_name
sponsor_contact_position
sponsor_contact_address
sponsor_contact_phone
sponsor_contact_fax
sponsor_contact_mobile
sponsor_contact_email
```

It *might* have made more sense to have an `FmcSponsor` model with all of these details—especially if the sponsor details were being used elsewhere. (This isn't necessarily a great example, but I think it explains the point: breaking things down properly into a sensible, normalized domain model is often the right way to go, but that's currently made difficult by koi not supporting `has_one` relationships in forms.

I'd like to get this into Koi when we can settle on a name for the field type.

**Comment by Obversity** [comment]
A couple of other field types worth mentioning:

### country

```
# _show_field_country.html.erb
<strong><%= t "simple_form.labels.#{resource_class.name.underscore}.#{attr}",
              :default => attr.to_s.titleize %>:</strong>
<%= ISO3166::Country[resource.send(attr)].try(:name) %>
```

We often have country fields on forms on websites. However, we don't include the country_select gem by default in Koi, meaning a field named 'country' will actually make the app throw an error because simple_form expects the gem to be installed. We also don't have a country form/show/index field in Koi to display the full country name, and this is something that Heath and Jason often insist on, so I think it'd be worth adding (a) the gem and (b) a specific :country field type to Koi. 

### show_field_select

Something like this: 

```
<%
  value = resource.send(attr)
  data = resource_class.crud.find(:fields, attr, :data)
  human_value = value
  human_value = data.invert.with_indifferent_access[value] if data.is_a?(Hash)
%>

<strong><%= t "simple_form.labels.#{resource_class.name.underscore}.#{attr}",
              :default => attr.to_s.titleize %>:</strong>
<%= human_value %>
```

Show fields in general need a bit of a review, but this one in particular is silly. When you make a 'select' field you add a `category: { type: :select, data: CATEGORIES }` to specify the data for the select field. This is often a hash of 'labels to display' and 'values we actually store in the database'. However, when rendering that on the show page, we just render the stored value, not the human friendly value. Heath/Jason often insist on this being human friendly, hence the above solution.

**Comment by pvawser01** [comment]
These suggestions seem reasonable to me. Country and select fields I have also experienced these issues with. The has_one_inline also makes sense. However, don't we have an association type that magically determines the association type and renders an appropriate view?

**Comment by dbaines** [comment]
> Any suggestions on what we call it in Koi?

I think `has_one_inline` is pretty self explanatory 👍

**Comment by pvawser01** [comment]
+1 for has_one_inline

**Comment by Obversity** [comment]
> However, don't we have an association type that magically determines the association type and renders an appropriate view?

We have a `_form_field_association` and a `_form_field_belongs_to` which appear to be doing very similar things. (I think the association one allows an `as` option, e.g. `{ type: :association, as: :radio_buttons }`, but I'm not certain.)

In either case, both fields are just for selecting an existing record, not for creating it on the fly. I.e. they're mainly useful for belongs_to associations.

**Comment by jsidoryn** [comment]
With the has_one_inline, is that an accepts_nested_attributes_for type thing? Also I'm assuming that validations will bubble up and be handled correctly? Is there anything else that we need to consider when creating other resources inline? 

Regardless, these three all look like good candidates. We don't necessarily need to design it in full in this ticket as it's really just for identification. Are there more things you'd like to check out @Obversity? Once done I think we can close and break up the work into separate RFC's.

**Comment by Obversity** [comment]
Yup, the has_one_inline is an `accepts_nested_attributes_for` thing. Validations should be handled. 

And yes, I think I'm about done!

Here's the TODO:

- has_one_inline
- country field type
- show_field_select
- work out the difference between :association and :belongs_to field types and possibly clean up

**Comment by Obversity** [comment]
@dbaines I seem to remember we had a Colour Picker field in some project. Would that be too heavy to want to pull into koi?

**Comment by dbaines** [comment]
@Obversity It was for hillsmith gallery, it worked pretty well I'd be all for adding to Koi

**Comment by jsidoryn** [comment]
could I suggest that we have a separate RFC based around front end components. i see adding in a colour picker as something that's more ornament focussed as needs some thought around interface etc and the ruby implementation is pretty straight forward. 

there's also things like looking at better date pickers and all sorts of form components that i think would be great to look at.

**Comment by dbaines** [comment]
Ornament should ideally only be concerned with the front-end of the application. Koi should be able to have front-end components without bringing them in to Ornament.

**Comment by pvawser01** [comment]
How often do we have a need for a Colour Picker? We don't want to be bringing in one off/custom features to KOI.
I would think this would fall into the custom functionality.
