### ISSUE TITLE
Improve csv generation

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#247]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR: #269 

# Summary

Rewrite csv generation to not use partials, to prevent server crashes. 

# Motivation

Generating a csv from a table with thousands of records will, at the moment, crash the server of most projects, depending on how many fields are on in the csv. This is because for each record, for each csv field, it needs to render a partial—which usually just displays the data as a string. 

For example, when generating a csv for a Users table with 50k records, and 15 fields in the csv, the server will have to render 750,000 partials before spitting it back at the browser. 

# Detailed design

For YourSAy, we solved this problem with a module that hijacks the index.csv request, and another module that reads from koi csv / field type config and outputs fields using plain ruby methods rather than partials. The plain ruby solution was orders of magnitude faster, rendering csvs in seconds where the partials solution was taking minutes and hogging server resources. 

See:
Controller module: 
https://github.com/katalyst/ysa-v2/blob/master/app/controllers/concerns/exportable_controller.rb

Model concern: 
https://github.com/katalyst/ysa-v2/blob/master/app/models/concerns/exportable.rb

The exportable model concern should be baked into koi and documented. In short, it adds a `Model.all.to_formatted_csv` method, which by default will read from koi crud, but which can also take a list of fields/method names to render the csv with. 

We should probably discuss the method naming convention for overriding csv field types, e.g. the equivalent of overriding the koi/admin_crid/_csv_field_date.html.erb, and how to go about baking it in is up for grabs—probably following whatever existing conventions there are for extending active record.

The other upside of this solution is that it'd let us more easily generate custom, well-formatted csvs for a given scope, allowing us to more easily created automate reporting tools, as we did for weekly Nuclear discussion csvs. 

We should think about any other csv features we want to add to this—for example, the ability to easily write the csv to a given file, say, in the tmp directory. 

# Drawbacks

The plain ruby solution is not as well tested as the existing partials solution. We'd also be less familiar with overriding the rendering of csv field types, so it would add a slight learning curve. 

# Alternatives

I'm open to any other suggestions on how to implement fast-but-flexible csv generation.

**Comment by jsidoryn** [comment]
Looks like a pretty sensible approach doing in Ruby. 

I've had a brief look through the code you linked to and it looks very tied to Koi. I'm wondering if you could break this into two parts. Make a more generic gem that takes an AR collection and performs the transformation on that directly and then separately integrates into Koi. 

So something like: 

collection.convert_to_csv(:title, :date, :user.name)

and have a way to configure column name transformation as config options through the gem and possibly transformation options (eg date format). 

Only half thoughts and something I don't understand in detail so forgive me if it's nonsensical. 

I'm also thinking if this might be a lower priority as it's not needed for all sites and the first site we get that requires this we can build then.

**Comment by Obversity** [comment]
Yup, it definitely is tied to Koi. It may be able to be extracted. I'll give it some thought as to whether it'd be worth gemifying! I suspect it'd be more work than it'd be worth at the present. 

"I'm also thinking if this might be a lower priority"

I don't see it as super low priority given that our current csv generation is a one-button server crash, if used on the wrong model—as happened with YourSAy last year, where I think we had to actually reboot the VPS. We *really* shouldn't be offering a feature than can crash a server.

**Comment by jsidoryn** [comment]
I guess I was assuming that there's no existing sites that would crash the server. This is marked against Koi 2.0 so are you thinking there is existing sites that would benefit from this and it's worth going back and fixing. Or is this more a risk ie client asks to add a csv generation on an existing site, it's not obvious how many records it's going to effect and bang, the server goes down.  

If this is the case then much higher priority.

**Comment by pvawser01** [comment]
I feel this is some what high priority. Any site with csv exports could crash in time as more data is added. Oliveri is one that comes to mind. They can export orders and contacts. As time goes by they will get closer and closer to a server crash. Also to consider is the shared servers. One client export could potentially bring down 30 odd client sites. Dark days. :(

**Comment by jsidoryn** [comment]
Let's do this! We'll consider this consensus and I've moved it to the ready column on the project board.

**Comment by Obversity** [comment]
Pull Request: #269

**Comment by Obversity** [comment]
Merged with PR #269
