### ISSUE TITLE
Code should be pulled into the project rather than sit in the koi engine

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#250]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR: 

# Summary

Some code that we often override or want to override could be generated in the project itself, rather than living in the Engine.

# Motivation

We often find ourselves overriding (or being unwilling or unable) to override or extend things in Koi.  This is not good. 

When Ornament gets bootstrapped, all its files are pulled into the project, where they can be edited per the requirements of the project. I'd like to trial taking this approach with several bits of koi, such as the Page and NavItem models and the Application / Crud controllers,.  

Koi is supposed to give us flexibility and productivity. Generating code in the project gives us a lot more flexibility.

# Detailed design

When a project is boostrapped, we should generate in the project, at minimum: 
- a Page model
- a Koi::AdminCrudController (or whatever all backend controllers inherit from)
- a Koi Application controller
- a koi view helper (aka ApplicationHelper)
- a koi application index (aka dashboard) 

Plus any other suggestions, things that we regularly need to work with.

This would let us customize things like the dashboard, add project-wide crud action methods (e.g. an Archive action), add application wide helper methods (e.g. current_region), add custom fields / validation to koi pages (e.g. page banners, or an og:image field) etc. 

# Drawbacks

This code may never get touched, and therefore be unnecessary bloat. 

# Alternatives

The alternative is that we leave things as they are, or find other easy ways of making these things extensible or overridable.

**Comment by jsidoryn** [comment]
I'm definitely in favour of this, I didn't even realise things like this was in engines. 

Could one way to work it like Devise does where you can generate the model and view code but if you don't it's hidden? I'm assuming for Devise it just moves it from a path that's hidden from you to one that's in your project.

**Comment by Obversity** [comment]
Yeah, it'd work similarly to devise. It's the way it currently works in Koi when you override a model. I.e. if I copy paste the `Page` model into `app/models/page.rb`, then it'll start using the code there, rather than the code in Koi.

**Comment by pvawser01** [comment]
I'm all for a devise like generator to add the files you want to override. I think the default should be leave in koi engine and if you want to override, then you run the generator to show the files locally. One thing I have always been a bit frustrated with Devise(not a big deal but..) is that when you run the , say view generator, it adds all devise views to your application. Usually I only need to override one or two not all. Would be goo if we could have a generator that could accept file names to override and if none supplied, show all. Just a show all option could make for a lot of clean up or bloat the application file view when there is no custom code required. Does this make sense?
