### ISSUE TITLE
More out-of-the-box alternative views

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#251]
- Start Date: 2017-02-13
- Owner: DB

# Summary

Improve the out-of-the-box experience with Koi by providing alternate views for the developer to use. 

# Motivation

Sometimes we need to make customised views for things such as Orders, Users etc. Most of these could be simplified enough and generic enough to make as a default. 

# Detailed design

We could create more crud views:

```
app/koi/admin_crud/show.html.erb
app/koi/admin_crud/show_order.html.erb
app/koi/admin_crud/show_product.html.erb
```

Maybe to make it cleaner we could use this sort of folder structure:

```
app/koi/admin_crud/show/default.html.erb
app/koi/admin_crud/show/order.html.erb
app/koi/admin_crud/show/product.html.erb
```

Once we have some alternative views we could define them in our model DSL like so:

```
crud.config do 
  config :admin do
    show  fields: [:name, :description],
          template: [:order]
  end
end
```

# Drawbacks

The more generic the views are, the less useful they can be. For example an `Order` could differ considerably between applications. We may just have to provide a smart default and then eventually override it anyway. 

# Alternatives

Maybe set up a system for defining new views quickly and easily for Koi to use in the application and leave it up to the developers to provide those views. 

Alternatively we could just leave it as-is, it's worked for us so far. 

# Unresolved questions

How many views do we want to provide? I think all the CRUD options are up for grabs. `index`, `show`, `edit`, etc.

**Comment by Obversity** [comment]
I like the idea of alternative views, but yeah, there's not enough consistency between projects for stuff like Products and Orders for this to work, I don't think. If we were to pick an ecommerce system to integrate with koi, perhaps as a 'plugin' gem, this would be less of an issue going forward.

Maybe we could just generate product / order etc templates in the project as files, which could then be copy pasted as needed into the required views, e.g. views/admin/orders/show.html.erb (or _show_fields.html.erb)? (Copy-pasting doesn't seem like a great system, but it's better than building from scratch, I suppose.)

**Comment by jsidoryn** [comment]
The developer experience is important and should be an important concern for Koi 3. 

I like the idea of this and never thought of it. This could be part of the prefab idea or could simply be a flag for a generator. 

We want to always have flexibility and it's safe to assume that across product / orders (for example) that things will differ from project to project. But there may be enough similarities that we could work out a good default that may get 80% of the way there. 

The added benefit here is that it may help for prototyping as well as even helping with scoping if there's some best practices we've already established. 

This is a broad topic that deserves some in depth thinking. The principles of flexibility and making sure that 'it's just rails' and can be changed are important. But we can gain efficiencies by bumping the starting point up a level.

**Comment by pvawser01** [comment]
I've been using rails admin for a personal project recently. While I'm not completely sold on way they do things there is one thing I do like. When configuring the admin layer for a model, if an association is added, the admin edit view will allow you to add/edit the associated records form there. We saw this requirement for Oliveri with products and such. This might be a nice compromise for what Dave has suggested. We could override the view/behaviour if needed but the default would serve us well.

**Comment by jsidoryn** [comment]
@pvawser01 this sounds like a different RFC? i'd support you writing one for this. would be ideal to have screenshots of how it works in your side project. 

any thoughts on generating big of functionality with generators? 

this RFC can probably focus on if there is any benefit from these types of generators. 

using the product / order example, could it be the concepts of cart, checking out and payment with stripe (or active_merchant) that could be generated with products and order just stubbed out with some generic fields as a starter. this could be useful. 

some others that come to mind are: 

contact form that generates a front end form, with editable content above and below that goes to a show page on success, builds the admin and sets up a mailer to mail the person a copy of their submission. 

faq generator. these seem to be pretty consistent and there's a bit to make them. should be able to generate them completely. 

blog. essentially a news_item with tags and a few sorting options on the front end. may not happen enough to warrant the investment. 

general thoughts?

**Comment by Obversity** [comment]
@jsidoryn I think this RFC was for backend templates, i.e. how an order show page might look in Koi to an admin. But it sounds like you're talking about front-end stuff? (Which actually could be a much more rewarding idea!)
