### ISSUE TITLE
review and remove any unnecessary / under-used depencendies of koi

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#252]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR: (leave this empty)

# Summary

If it's not being used or hardly being used, it shouldn't be there. 

# Motivation

See above. Let's see if we can trim the fat!

# Detailed design

For example: 

- I've noticed the 'rails-observers' gem is only used once in the project, and I'm pretty sure the code could be rewritten to regular rails model callbacks. 

- We rarely use the active_model_serializers, although we have occasionally had use for it with Fringe. Perhaps we should disable it in the generators

Basically, we should go through each gem one by one and see where in Koi it's being used, and determine whether or not we should keep it. I'm positive that koi is heavier than it needs to be. And let's lock things to versions while we're at it!

# Drawbacks

- Removing dependencies risks breaking koi if we don't test thoroughly enough. We'll want to keep an eye on the gems we've removed. 

- Locking things to versions means we might not get updates that could be useful. 

# Alternatives

We leave it as is. Koi isn't impossibly slow to work with, and I doubt its dependencies are the bottleneck, but until we start culling, we won't know.

**Comment by jsidoryn** [comment]
'Trimming the fat' would be a great outcome for Koi 3. Going through them is also a way to better understand what's there and why. 

Would it be worth also reviewing whether the gem is the best gem for the job or if the gem version is the right one?

**Comment by Obversity** [comment]
Asking whether a gem is the best gem for the job is a much bigger task, but if anything really obvious jumps out, then sure, definitely. I'm wary of picking new gems just because they're flavour of the month, but there may indeed be better alternatives to some of the things we use.

They should be individual RFCs, if we find any, so the pros and cons can be assessed.

**Comment by jsidoryn** [comment]
hopefully no one is in favour of picking gems just because they are new and shiny. 

you're right though, has the potential to broaden the rfc way too much. should be separate rfc's as you say.
