### ISSUE TITLE
Pull Navitem information in to Page views

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#253]
- Start Date: 2017-02-13
- Owner: DB

# Summary

The relation between `NavItem` and `Page` can be very confusing to most people. We could remedy this by exposing some information about the `NavItem` to make this clearer. 

# Motivation

* People delete NavItems and are confused when the Page is still lingering around in the background 
* Why can I make a NavItem hidden but I can't see if the page is hidden when I edit the page? 
* Another case is when creating a page, then having to go back to the sitemap to hide it. Ideally we could it all on one page. 

# Detailed design

When editing the page we could expose `NavItem` information and even make them editable. 

![navitem-on-pages](https://cloud.githubusercontent.com/assets/685024/22872816/e75a2166-f20b-11e6-9f1e-5ea199fb0987.jpg)

UI still to be considered. It could live in a panel, be pushed to a sidebar, or even its own tab. 

The user can now create or edit their page and update the NavItem details in one step. 

# Drawbacks

Possibly slower to render the edit page as it has to lookup NavItem information. 

# Alternatives

Rather than making it the same form it could be a modal pop-up form on the edit page view. 

# Unresolved questions

How much do we expose here? All of it? Just the basics?

**Comment by kippo** [comment]
@David I've created a #RFC for the slug editor part of this David as I wanted to explore the addition of enabling redirects when editing the pages slug. You can see this at #256.

**Comment by dbaines** [comment]
@kippo sounds great 👍

**Comment by Obversity** [comment]
@dbaines It wouldn't be slower to render by any meaningful margin, so I think we're safe there. Sounds good!
