### ISSUE TITLE
add rack-cache to the included gems so dragonfly doesn't have to regenerate thumbs for everything

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#254]
- Start Date: 2017-02-13
- Owner: BP
- RFC PR:

# Summary

Adding the rack-cache gem prevents dragonfly from regenerating image thumbnails etc on every image request.

# Motivation

Caching images greatly reduces server load and significantly improves user experience on image-heavy sites, as images will 'download' faster. 

# Detailed design

It seems to be as simple as adding the rack-cache gem and adding a line of config. See here:

http://markevans.github.io/dragonfly/rails#caching

# Drawbacks

There may be side-effects of the rack-cache gem that we're not aware of. 

# Alternatives

Using S3 to host images by default is a pretty good alternative, but it's a lot more costly, in $$$ and setup time.

**Comment by pvawser01** [comment]
Not sure I agree with the S3 comment. S3 is pretty simple to set up. It also removes the need for server disk space. Consider something like yoursay where images were on the server. S3 will remove load and disk space from the application server. Also, if you consider scaling, if images are on the server, if a slave server is needed down the track, you would then have syncing issues. Personally I think S3 should be the default set up. The only issue I see with that is if the client wants a secure customized URL to access files. If files are to be served from the application file system, then you should really be using either a dedicated util server for assets or a very large mounted disk just for files.
Just my 2 cents worth.

**Comment by Obversity** [comment]
Yup, I actually agree that S3 would be a better default than hosting them ourselves. This might be worth an RFC, detailing the pros and cons, and how much it might cost clients. Probably more of a Koi 3 thing than a Koi 2 fix, IMO. 

In the mean time, the rack-cache gem is a drop-in fix to some sites that are very image heavy, assuming disk storage isn't an issue—which I suppose on some of our shared servers it is.

**Comment by jsidoryn** [comment]
Yep, I think the move to S3 warrants some more discussion as I've got a few pros and cons to add. Best to focus on this one as it is. 

@pvawser01 did you have any objections or comments on the addition of rack-cache?
