### ISSUE TITLE
SEO Tabs

### ISSUE THREAD

**Issue by kippo** [katalyst/koi#257]
- Start Date: 2017-02-15
- Owner: BP
- RFC PR: 

# Summary

Get the SEO tabs working

# Motivation

Clients need SEO. At the moment, we hook it up manually every time, mostly copy pasting from existing projects. This should be hooked up in Koi. 

# Detailed design

Look at previous projects where SEO is functioning as intended (maybe Oliveri?) and pull it into koi to work out of the box.

# Drawbacks

None. 

# Alternatives

Regardless of whether our approach to SEO is managed through settings, we still need to hook up the backend to the frontend somehow, so it's still worth doing. 

# Unresolved questions

Worth visiting whether we need to create empty settings if fields are blank. Probably outside of the scope of this, and should be tackled when we tackle settings.

**Comment by dbaines** [comment]
The seo partial has been added to Ornament (as of v1.2.4) so it's ready-to-go on the front-end. 

Koi (or the application) needs the `seo` method defined somewhere. That's what the seo partial looks for as it's source of truth, then falls back to various yields, then back to hard-coded values in the partial. 

Maybe to streamline it we could add a concern or something like `seoable` that shows the SEO tabs and wires it all up in the backend. Or do we want it to be enabled for everything by default? 

Here's the seo partial in Ornament if you want to peruse the code:
https://github.com/katalyst/ornament/blob/master/lib/generators/ornament/templates/app/views/layouts/_seo.html.erb

And some docs detailing the yields it reads from:
http://ornament.katalyst.com.au/styleguide/seo

Semi-related is the SEO role bug #192 
Should we merge that one in to this one or keep them seperate?

**Comment by pvawser01** [comment]
Could it be available for everything but only render if there exists configuration in the backend. I think I'm understanding this right. On if backend data exists off if none.

**Comment by dbaines** [comment]
@pvawser01 Yep that's how it works, if `seo` is defined it uses those, then falls back to `yields` defined in the view, then falls back to hardcoded values. 

Would also be good to extend the seo tabs with general meta data like Facebook share image etc.

**Comment by Obversity** [comment]
Done with PR #265
