### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by kippo** [katalyst/koi#258]
- Start Date: 2017-02-14
- Owner: KB
- RFC PR: (leave this empty)

# Summary

Build a customisable dashboard allowing users to see important information and perform useful features.

# Motivation

We have the concept of a dashboard but its not utilised at the moment. It's assumed clients would like this type of feature.

# Detailed design

![img_1594](https://cloud.githubusercontent.com/assets/4476272/22918297/9a97bce8-f2d9-11e6-974d-8013b5d5f4b7.JPG)

![img_1593](https://cloud.githubusercontent.com/assets/4476272/22918294/99772d1c-f2d9-11e6-910a-5e000e859fb3.JPG)

The dashboard would be built up of individual widgets that can be added and removed by the user.

Each user has there own dashboard customisations.

Each widget has settings that allow it to be modified in some way. For example a bounce rate widget may let you edit the name of the widget, the bounce rate time frame and its prominence on the dashboard.

Multiples of the same widget can be added to the dashboard allowing variations of the same widget to appear at the same time. For example I may have an activity widget that lists out all new users and an activity widget that lists out all new orders and contact form submissions.

The title of the widget can be editable so that users can name them something that makes sense to them given the customisations they have made to the widget. For example you would name an activity widget that on shows new users as "New Users".

There are a number of different widgets that we could create and more could be added down the track, either customised specifically for the project or generically to KOI.

These widget could be broken down into the following groups. Each could probably be considered it's own feature but I'm keep them here for the time being.

### Shortcuts

The ability to create shortcuts to different sections of the CMS. For this to work we can probably just have the user give the shortcut a name and provide the link that they want it to go to.

### External Analytics/Stats

Analytics and stats pulled from places like Google Analytics, Campaign Monitor or Add This.

### Internal Analytics/Stats

Analytics and stats pulled from KOI itself. It may be that we end up pushing a lot of this data into Google Analytics in the future and then pull it back into KOI. If this happens then that data would probably be considered at external data.

### Activity

A list of important things that have happened on the site. For example a new user has signed up.

### Social Mentions

This was already in there but doesn't seem to work anymore. The idea would be to pull in any mentions about the company in the social media space. @dbaines informs me that we may have issues around authentication here.

### Alerts

A system to alert users to important things. For example a SSL certificate is about to expire.

### KPIs

The ability to set KPIs and then visually see how close you are to reaching them. For example we might want to achieve $20,000 of sales this month.

# Drawbacks

Unknown for now.

# Alternatives

Unknown for now.

# Unresolved questions

How would we lay out this page page. The obvious choice would be masonry but I'm not a huge fan of this as I believe the staggered design of this makes the page harder to comprehend. Geckoboard uses flexbox to created a more structured layout although I'm not sure if this would work given the variability of the layouts that could be created. See a Geckoboard example [here](https://www.geckoboard.com/learn/dashboard-examples/digital-marketing-dashboard-example/live-dashboard/).

**Comment by Obversity** [comment]
A better dashboard definitely sounds like a good idea, and I like the idea of widgets as a way to improve it. 

A widget system is doable. The hard bit will be the contents of those widgets, and how customizable the different widget types need to be. 

It might be possible to have a couple of koi default widgets (like a Shortcuts widget) and then have other widgets that we build on a per-project basis. For example, different projects require different analytics, so just having a generic analytics component wouldn't be worth much, and a fully customizable analytics would be too hard to build IMO, but having different graphs etc you can pull in as widgets that we build on a per project basis could work. I.e. the customer might want to track their sign ups, so we build a signup graph and make it widgetable.

**Comment by kippo** [comment]
@Obversity Yeah that the assumption at the moment. A suite of prebuilt slightly customisable widgets alongside side widget built exclusively for specific projects. 👍

**Comment by pvawser01** [comment]
@kippo @Obversity There is something called Dashing. Developed by Shopify it is a rails engine that is customisable and could be added to koi. It does have issues with IE as  the docs mention, it relies on server sent events. However, we could possible, with koi3 , using Rails 5 engineer it to use action cable. Alternatively, we could just take the concepts they have used and build our own following the same widget structure they have come up with (copy it). I've used Dashing before. You basically pic a display widget type and pass custom data to it. I had live newrelic feeds going to a custom dashboard with live server processes displayed as well. There are endless possibilities. Just if the UI is what we want is the question..

**Comment by dbaines** [comment]
I've started working on some front-end code for dashboard widgets:
https://github.com/katalyst/koi/tree/feature/dashboard-analytics

There is a list of hashes that the feed in to the dashboard, here's some sample code:

```ruby
  widgets = [{
    title: "Weekly pageviews",
    type: "chart",
    size: "Small",
    chart: {
      type: "line",
      labels: ['5', '4', '3', '2', '1'],
      series: [
        [1000, 1050, 1280, 1100, 1250]
      ],
      series_labels: ["Pageviews"], 
      show_variances: true,
      settings: {
        simple: true
      },
      chart: {
        showArea: true,
        low: 0
      }
    }
  },{
    title: "Subscribers",
    type: "chart",
    size: "Small",
    chart: {
      type: "bar",
      labels: ['5', '4', '3', '2', '1'],
      series: [
        [12500,12520,12800,12820,12700]
      ],
      series_labels: ["Subscribers"], 
      show_variances: true,
      settings: {
        simple: false
      },
      chart: {
        showArea: false
      }
    }
  },{
    title: "Latest Unfilled Orders",
    type: "list",
    size: "Large",
    list: [{
      label: "Item 1",
      actions: {
        "View": "#"
      }
    },{
      label: "Item 2",
      actions: {
        "View": "#"
      }
    }]
  }]
```

This will produce some widgets like so:

![screen shot 2017-06-08 at 5 28 43 pm](https://user-images.githubusercontent.com/685024/26918241-47966940-4c70-11e7-9c36-82d034b63855.png)

Each widget has a "back" view that shows when clicking on the cog, they all have generic widget settings like name and size, and each widget type has their own settings:

![screen shot 2017-06-08 at 5 29 04 pm](https://user-images.githubusercontent.com/685024/26918247-4dec32b6-4c70-11e7-884a-faf99e5a0db0.png)

So far the widget types I've created are:
* chart (Using chartist.js to display very simple charts)
* list (A list of items with actions)
* twitter (A twitter feed)
* message (Generic text widget)

There are also some generic widget types that will later be taken advantage of:
* loading
* errored

Each widget type has a partial eg: `/app/views/koi/application/dashboard_widgets/twitter.html.erb`  
Each widget has an optional partial to contain it's widget-specific settings, eg: `/app/views/koi/application/dashboard_widgets/twitter_options.html.erb` 

If you pass in a widget type that doesn't have an associated partial it falls back to the `unknown_widget_type` partial, which just says the widget has an unknown type. 

Moving forward we'll need to look at slowly replacing the hard-coded data configurations with actual data from somewhere else, hooking in APIs, saving configurations either to localStorage or to against the user record etc.

**Comment by jsidoryn** [comment]
@dbaines these look pretty cool.

we've just found out we've got some budget to build some dashboard features for yoursay. this should be great as will help define some real use cases to solve for that project and then we can push our learnings back into koi 3. 

or build generic and apply to yoursay...

either way, worth a chat about how best to proceed with this.
