### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#272]
- Start Date: 2017-02-27
- Owner: DB
- RFC PR: N/A

# Summary

The responsive UI has set the groundwork to allow for keyboard shortcuts. 

# Motivation

Sometimes it's nice to just press letters on the keyboard to do things. See Jira for example. 

# Detailed design

### Current shortcuts:

Utilising [keyboard.js](https://github.com/RobertWHurst/KeyboardJS) we can use keyboard shortcuts to trigger javascript events.

| combination | result |
|---| --- |
|`alt + m`|Toggle the menu|
|`esc`|Close menu, close lightbox|

Some proposals could be:

* Trigger the "new" action on index listing 
* Trigger the "save" action on a form listing 
* Focus on search 
* Switch tabs 

A lot of Koi will need an accessibility pass to make sure everything is focusable and keyboard-accessible. It should be already but tabindices might need reviewing/testing to make sure tabbing through things makes sense. 

It's probably worthwhile taking some time to investigate what keyboard shortcuts are used in other web applications and seeing if there's any common shortcuts, recommendations or best practices. 

# Drawbacks

Colliding with user-defined shortcuts or browser shortcuts is always problematic. 

# Unresolved questions

This is really a super-user feature. Would people use it? Would we use it?

**Comment by Obversity** [comment]
@dbaines alt+m is a really awkward combination for a menu for me. Usually I'll want to be using my mouse when I need a menu, and I agree that it'd be nice to be able to open the menu while my mouse is travelling across the screen, thereby saving a click, but to press alt+m conveniently I need my right hand—which I also need for the mouse, unless I can browse the menu with arrows!

(Can I browse the menu with arrows? I presume you'd have mentioned if so.)

**Comment by dbaines** [comment]
@Obversity You wouldn't use arrows to browse the menu would you? The only instance I can think of using arrows to navigate on the web would be some form elements like radio buttons. Arrows are generally used to scroll I wouldn't want to hijack that from the user. The menu is keyboard accessible you can tab between links and press enter/space to trigger the action. 

If you can provide some links to other things using arrows to navigate that would be great. 

Either way all keyboard shortcuts are up for grabs, suggest new ones!

**Comment by Obversity** [comment]
@dbaines Good point! I actually can't think of any menus that use arrows for navigation. That said, I can't think of any menus that are infinitely nested like this, either. My problem with tab is that you can tab off the end of the menu and lose track of your tab. But yes, tab works. 

As suggested in your other RFC, a search bar would mitigate the need for this entirely!

**Comment by jsidoryn** [comment]
Seems like something that might be good to have in Koi. I'm not sure we're typical users though and might be worth going to clients to see what they want. Might also be a bit hard to pin point without seeing how Koi 3 turns out so might be something to look at a bit later. 

The main one for me, which stretches this feature substantially, would be to have some sort of site wide power search (not sure if this is the same as the RFC, could you add a link?). This could involve having a search that searches through modules for quick navigation to different areas of the site but also to titles of content etc. So a quick way to jump around the backend.

**Comment by dbaines** [comment]
@jsidoryn The RFC Bill referenced was for the [menu filter](https://github.com/katalyst/koi/issues/274), it's already been built, approved and merged in to master 😄 

It would be amazing to extend it in to a spotlight-like feature though.

**Comment by jsidoryn** [comment]
got it and understand the conversation now. 

that's pretty great as it is and already gets much of the way there. 

spotlight feature is definitely a separate feature.

**Comment by jsidoryn** [comment]
@dbaines if it's already in master, would you mind closing the ticket and linking in the pr. cheers
