### ISSUE TITLE
Ordering of non-database columns in koi index view is broken

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#273]
Often we use non-database fields in our koi listing pages, e.g.

```ruby
index fields: [:full_name]
# ....
def full_name
  first_name + " " + last_name
end
```

Ordering by this column in the UI doesn't work at the moment. We should either (a) disable ordering for non-database fields, or (b) implement ordering for these fields (which would be a lot more work, and would be a bad idea for tables that have a very large number of records, since you'd have to do the sorting in Ruby.)

**Comment by dbaines** [comment]
I like it. How do you see us managing this? 
Would we compare the title to the list of form fields? Something like this:

```
def sortable(...)
  if !resource_class.crud.find(:admin, :form, :fields).include?(title)
    content_tag(:span, title)
  else
     ...
  end
end
```

Or would it be safer to manage a seperate list of hard-coded fields to check against? eg. an `order_id` field might not appear in the form fields so checking against that list would make this field unorderable, even though it's possible to order by it. 

Or am I over-thinking it and there's already an easy way to tell?

**Comment by Obversity** [comment]
Something like

```ruby
resource_class.column_names.include?(attr) 
```

Should do the trick, I think!

**Comment by dbaines** [comment]
@Obversity Yep that did the trick! Works perfectly for me. I've created a pull request: https://github.com/katalyst/koi/pull/277

**Comment by dbaines** [comment]
Merged in to master
