### ISSUE TITLE
Menu filter

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#274]
- Start Date: 2017-02-27
- Owner: DB
- RFC PR: https://github.com/katalyst/koi/pull/276

# Summary

Add a filter input to menu to quickly find menu items / modules 

# Motivation

Sometimes our module menus can get lengthy. This would be a nice super-user feature to quickly find what you're looking for (assuming you know what it's called)

# Detailed design

A simple little search box in the menu:

![menu-filter-default](https://cloud.githubusercontent.com/assets/685024/23344804/d21bcc6a-fcd2-11e6-8230-3c32e2bdeb80.jpg)

When you start typing it automatically starts filtering the list:

![menu-filter-sitemap](https://cloud.githubusercontent.com/assets/685024/23344808/e1bcb526-fcd2-11e6-94ab-6e1a1deb463c.jpg)

It would be smart enough to look for all menu items irrelevant of how nested they are:

![menu-filter-superhero](https://cloud.githubusercontent.com/assets/685024/23344815/f33e0912-fcd2-11e6-8997-06e2fb11fba5.jpg)

# Drawbacks

This could be confusing to users. Why is there a search box in the menu? 

# Alternatives

Quite a large alternative could be to implement a spotlight-like Koi search feature to return all sorts of things quickly in the UI like modules, records, settings etc. 

# Unresolved questions

Would people use this? Is this too super-usery? Would this benefit a small site? Maybe it could be a configurable setting in `koi.rb`?

**Comment by Obversity** [comment]
This would be awesome! On large sites with lots of modules it would definitely make sense. 

I don't see this as being too super-usery. If you know how to use google, you know how to use a search box. We'd just need to make sure that the fuzzy-finding is good.

**Comment by dbaines** [comment]
My current thinking is that the search results will be compiled as a flat list of links, eg. You wouldn't see the parent links like "modules", "advanced" or "assets" in the list returned but you would see "super heroes", "images", or "clear cache". 

The only concern I have with this is in the case of a site with a massive navigation you might have multiple modules in nested menus that maybe the parent or group that it's in would be relevant to the user. 

For example, you might have "news" under "YourSAy" and "Nuclear" that are just shortcuts to a pre-filtered news section, but when the menu is filtered it just shows two "news" items. 

Would something like this be helpful? 

![menu-filter-group-labels](https://cloud.githubusercontent.com/assets/685024/23348449/22765f28-fcfa-11e6-949c-b8410159e7f2.jpg)

And if so how far back should it go? Only show the direct parent? Or the main parent? Or the whole lot? eg. `Super Heroes > Another Group > Something Else`:

**Comment by Obversity** [comment]
Yup, I was thinking a flat list as results as well, but duplicate results would definitely be an issue. A breadcrumb style thing like you suggested could definitely work, but there might not be enough space to show the whole lot, yeah. 

Say you had a structure like

```
- YourSAy modules -> 
        - content -> news
        - users
        - etc

- Nuclear modules -> 
       - content -> news
       - forms -> etc
       - etc
```

It'd be the top level thing that'd be more useful to see. But maybe this isn't how we'll end up using infinitely nested module items. So yeah, I dunno!

**Comment by dbaines** [comment]
I think the whole lot doesn't look too bad actually

![menu-filter-ancestors2](https://cloud.githubusercontent.com/assets/685024/23348971/0aacb5ea-fcff-11e6-8547-eba4285fab2c.jpg)

The code will loop through each parent of the result and build up a breadcrumb-style list of folders it's in. 

I've added a setting to `koi.rb` so you can turn the filter off entirely, maybe it could be extended to control the breadcrumb feature:

```ruby
Koi::Menu.filterable = true
Koi::Menu.filter_breadcrumbs = 1..2 # can be false or 0 to turn off entirely, can be "all" for everything
```

Maybe that's getting in to over-engineering territory.

**Comment by Obversity** [comment]
Yeah, it doesn't look too bad hey. Sounds great! I'm all for it.

**Comment by kippo** [comment]
Love this idea.

**Comment by dbaines** [comment]
Merged in to master
