### ISSUE TITLE
Dynamic partials for crud pages

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#278]
- Start Date: 2017-02-28
- Owner: DB
- RFC PR: N/A

# Summary

Add some more overridable partials to the index listing and form page. 

# Motivation

To add something new to the listing page or the form page you need to potentially override the entire page to add what could be quite small things. Maybe you want a notice at the top of the index listing page? Maybe you want a panel in the sidebar just for one module? Wouldn't it be nice if you could just create `/app/views/admin/categories/_index_sidebar.html.erb` and have it just pop in and sort out all the layout issues by itself? 

# Detailed design

The main crud pages will be updated to allow a dynamic sidebar based on the availability of a sidebar partial. If the partial exists, the layout gets updated and injects the sidebar on the right side of the page. 

I also like the idea of being able to inject content in various places in the UI in the form of partials in the application. 

### Index listing

```
_index_above_list.html.erb
_index_below_list.html.erb
_index_sidebar.html.erb
```

![index_partials](https://cloud.githubusercontent.com/assets/685024/23387477/a9886f30-fdac-11e6-9ad2-c80678cb2a9b.jpg)

You can add custom listing actions either inline per list item or as a whole at the top of the list:

```
_index_fields_custom_actions.html.erb
_index_custom_actions.html.erb
```

![index_partials_actions2](https://cloud.githubusercontent.com/assets/685024/23440247/dfcef762-fe6a-11e6-8231-88a43615b957.jpg)

You can now add a primary action on any crud page that appears near the title, and add a description under the title:

```
_index_under_title.html.erb
_index_title_actions.html.erb
```

![index_partials_title copy](https://cloud.githubusercontent.com/assets/685024/23442598/71f88b68-fe79-11e6-8dd1-0bc5f65e214a.jpg)

### Form page (edit/new)

```
_form_above.html.erb
_form_below.html.erb
_form_sidebar.html.erb
```

![form_partials](https://cloud.githubusercontent.com/assets/685024/23387512/e302fe24-fdac-11e6-9d34-bb7f8406c9c3.jpg)

### Show page

```
_show_above.html.erb
_show_below.html.erb
_show_sidebar.html.erb
```

You could use a sidebar to show orders for a user:

![show_partials](https://cloud.githubusercontent.com/assets/685024/23387640/cbbdf70e-fdad-11e6-8348-ad898d2ecb89.jpg)

Or the below partial to show the products for a category:

![show_partials_relation](https://cloud.githubusercontent.com/assets/685024/23388290/30021b2a-fdb1-11e6-9266-fb40e9cfee9a.jpg)

This allows quick and easy methods of exposing content or related information without having to worry about overriding important files and breaking update paths. 

### Where do the partials go?

In the usual koi fashion, they can go in `app/views/koi/admin_crud` and affect ALL koi views, or you can instead put them in `app/views/admin/<model>` to affect just that one module. 

# Drawbacks

It's a little hidden. Because there's so many options I think populating them all in the dummy app would get pretty full-on, just look at that index listing screenshot!  

We could add a wiki page that details partials you can use to alter the layout. 

# Alternatives

I considered building this in to the model DSL, but I like the idea of just creating partials in the application that push in to the CMS if available. I couldn't figure out an easy to understand format for the DSL to designate yield areas and which partials go where. This way we have designated areas for partials and it's quite straight-forward to use. 

# Unresolved questions

The `index`, `form` (which itself is used for `new` and `edit`), and `show` crud views are my main target but I'm happy to hear suggestions for anywhere else that would benefit from this. 

Do you think the sidebar should be sticky on scroll? I guess it depends on the content. This could be a seperate RFC to allow sticky sidebars.

**Comment by Obversity** [comment]
This looks amazing. Definitely got my vote. Do you need any help implementing this or are the screenshots actual screenshots? 

On this topic, I'd love the ability to be able to add additional actions and relations to the index view. 

Earlier today I wanted to add an additional csv download button for Fmc Idea voters.

![image](https://cloud.githubusercontent.com/assets/7999019/23392295/9127f38e-fdca-11e6-87ef-1d0cb2ba97f6.png)

I had to override the `fmi_ideas/_index_actions.html.erb`, and then work around the exiting code copy pasted from Koi. TL;DR: it shouldn't be that hard to add additional actions to the index view. 

Same with the form (where we could, say, add a 'partial save' button), or the show (where we could add, say, an 'archive' button). 

Same again with the per-item actions/relations in the index view:

![image](https://cloud.githubusercontent.com/assets/7999019/23392374/0db873ec-fdcb-11e6-87de-dd351ad48a0d.png)

It'd be nice to be able to add additional links here easily.

**Comment by dbaines** [comment]
@Obversity 

It's real! I [pushed up the branch](https://github.com/katalyst/koi/find/feature/278-DynamicPartials) but haven't made a pull request yet, I thought it would be a bit cheeky to do one before anyone saw the RFC for it. 

I think [relations should already work in crud config](https://github.com/katalyst/koi/wiki/Crud-Config#index-relations) but let me know if that doesn't work. 

From a design point-of-view, the relations list could do with some love. I wonder if they should be in actions or if they should have their own column. 

Similarly I think actions could be added to the DSL. Then again `actions` already refers to something different in the DSL (it refers to being able to show the show/edit/delete buttons) 
Also if it's in the DSL it might be awkward to determine things like button colours etc. Maybe it would be better to have that partialised. I can definitely add it to the list. 

It's super easy to build on this, I made a new view helper `partial_with_wrapper` that safely falls back to doing nothing if there's no partial available. [Code is here](https://github.com/katalyst/koi/blob/feature/278-DynamicPartials/app/helpers/koi/application_helper.rb#L137) if you're curious. Not sure if application_helper was the best spot for it. 

Then you just add your partial to the view:
```
<%= partial_with_helper do -%>
  <div class='container-element-that-controls-spacing-and-positioning'>
    <%= render "my_custom_partial" -%>
  </div>
<%- end -%>
```

**Comment by dbaines** [comment]
@Obversity 

Thinking about it more I agree  an area for actions would be good. Since not all actions there are technically relations. I know in one of our sites I've seen custom order processing buttons appear here, which could only be done by overriding that partial. So I've added a spot for custom actions:

`_index_fields_custom_actions.html.erb`

Similarly I've added an area for custom actions at the top too:

`_index_custom_actions.html.erb`

![index_partials_actions2](https://cloud.githubusercontent.com/assets/685024/23440247/dfcef762-fe6a-11e6-8231-88a43615b957.jpg)

**Comment by dbaines** [comment]
You can now add a primary action on any crud page that appears near the title, and add a description under the title:

```
_index_under_title.html.erb
_index_title_actions.html.erb
```

![index_partials_title copy](https://cloud.githubusercontent.com/assets/685024/23442598/71f88b68-fe79-11e6-8dd1-0bc5f65e214a.jpg)

This is the index page but I've added it to index/form/show. 
Ideally you would only ever add one primary action, if you need to add multiple actions to the title my recommendation would be to put it in `under_title` rather than `title_actions`. It gets too busy otherwise.

**Comment by dbaines** [comment]
Merged
