### ISSUE TITLE
Listing Filters

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#279]
- Start Date: 2017-02-28
- Owner: DB
- RFC PR: N/A

# Summary

Allow the user to filter the index listing to show only records they are interested in.

# Motivation

It's been requested in the past, we have implemented specific custom filters when necessary. It would be nice to have something out of the box and configurable though. 

# Detailed design

Another button appears in the listing action bar:

![filter_index](https://cloud.githubusercontent.com/assets/685024/23391173/e169b470-fdc2-11e6-85e2-e558c5eaef4b.jpg)

When pressed, the user is presented with options to filter these records:

![filter-options](https://cloud.githubusercontent.com/assets/685024/23391177/ec9567f4-fdc2-11e6-87b8-8f648c8cf17b.jpg)

When filtering, the user is shown a small notice at the top of the screen indicating they are looking at a filtered view:

![filter-warning](https://cloud.githubusercontent.com/assets/685024/23391196/00930d6a-fdc3-11e6-8a64-824c0719ce7a.jpg)

We don't want any and all fields to be filterable so we need a way to determine what to show in the filter modal. See unresolved questions for a few ways this could work.

# Drawbacks

None that I can think of, anyone else? Would it impact the server load? Configuration overhead? 

# Alternatives

An alternative is to replace the listing table with something like [datatables](https://datatables.net/) and get in-browser filtering, pagination, searching and such. 

# Unresolved questions

### Specifying what to filter

Something like this could work:

```ruby
config :admin do
  index filters [:gender, :status, :powers]
end
```

The issue with this is that we may want to control the field type. We could infer it from `crud.config fields` but if we ever want those to be different we may need a way to specify field types:

```ruby
config :admin do
  index filters { gender: :select, powers: :radio_buttons }
end
```

### Search impact

For searching though, we already have `has_crud searchable: [:first_name, :last_name]` to show a search field and control what fields to search against.

We could retain this and just pop search in there when `has_crud seachable` is available. 
If `has_crud searchable` is available but no filters are defined, do we show them in the filter modal still or just pop search out in to the main UI like it currently is? 

The other option is to deprecate this and move search in to filters, something like this might work:

```ruby
config :admin do
  index filters: { search: [:first_name, :last_name], gender: :select, powers: :radio_buttons }
end
```

**Comment by jsidoryn** [comment]
I think as a feature this is definitely something we'll want to include in Koi 3. As far as the final UI it's also something that @kippo will be looking at in the UI review. 

I quite liked the Datatables implementation you did for Combat Sports. I think this needs a bit more thought also to pin point the use cases.

I think the main use case is that a person is looking for a record to edit or delete (or some other action). For this the databases UI would be best. 

Another use case is if they are trying to get an idea of the collections of records eg if they are trying to see all Super Hero's with X-Ray powers. For this the filtering approach you've described works better. 

The filtering approach might also be good if it ties in with a way to define the fields for a CSV export.
