### ISSUE TITLE
Making 'admin_url' field required for nav items

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#285]
- Start Date: 2017-03-03
- Owner: BP

# Summary

Make the 'admin_url' field of module nav items required for a better user experience for our clients.

# Motivation

We as developers / admins often don't fill in the admin_url field because it takes time and we're busy. However, if the sitemap is to be a proper 'sitemap' for both the backend and the front-end, for usability's sake it should be possible for admins to click on any item in it and be taken to the relevant page in Koi to edit / manage the record / listing. This isn't often the case because we rarely fill in this field. 

It's a tradeoff between better usability for our clients, and an extra few minutes of our time every time we do sitemap updates. But given that it's probably much easier for us to find this url than it is for clients to do so, and given that the client probably has to do it a lot more frequently, it seems worth it. 

# Detailed design

We add

`validates :admin_url, presence: true`

To `nav_item.rb`

We'd also have to move the admin_url field to the 'basic' tab when creating/editing nav items, so regular admins can see it. 

Then, every time we create a module nav in the sitemap, we are forced to link it to the relevant part of Koi. For example, if it's an FAQ page that you're adding to the nav, it should be a link for the admin to be able to edit the FAQs. If it's a contact form or a submission of some other kind, the url should be a link to where they can view / manage those submissions. 

# Drawbacks

It takes time and effort to find the relevant part in koi, copy the path and paste it in. 

# Alternatives

We keep it as is. It's not harming anything as it stands. 

# Unresolved questions

Would we want to do this for folder nav items as well?

**Comment by dbaines** [comment]
I don't think it would be possible for folder nav items since they are usually just a grouping. eg. Where would a folder "heaver navigation" go?  
What about external links? Would we just use the same URL? 
I guess at the end of the day if we really need to get around it we can just use "#" 

I dig it

**Comment by Obversity** [comment]
Yeah, it wouldn't be relevant to lots of folder nav items. But for stuff like "Fund My Community" in YourSAy, you could link to /admin/fmc_rounds. And yeah, worst case scenario you just use '#'. 

External links is a good point. And yup, I suppose it could just be the same url. I think that'd feel reasonable.

**Comment by jsidoryn** [comment]
It's worth mentioning that the site map is only a representation of the navigation on the front end and is not intended to be a way to edit all sections of the site. 

That being said, if it a appears in the sitemap, there's an expectation that you can click on it to edit it in the admin. This seems like a good idea and adding validation ensures consistency. 

Excluding folders seems sensible as they are just for grouping. You could also imagine a possible future version of the sitemap where folders could be open and closed and that would be their function if selected. 

Is there anything else that needs to be excluded. If not this might be ready to lock down.
