### ISSUE TITLE
Mega Menu Navitem

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#297]
- Start Date: 2017-02-09
- Owner: DB
- RFC PR: 

# Summary

Better mega menu management. 

# Motivation

Mega menus are hard. 
The way we've done them in the past has been inconsistent and always kind of hacky. 

Depending on the requirements of the website we may need any of these sorts of configurations:
* Only one top-level navitem is a mega menu, all others are regular drop-down menus
* All top-level navitems are mega menus. 
* There is one image inside the mega menu to represent the section
* There are many images inside the menu to represent each link
* There is a heading that differs from the navitem name inside the menu to represent the section, could be a long-form label for example 
* There is description content in the form of WYSIWYG, Text or String
* Each link may have a short description associated with it

Some examples of koi sitemap-managed mega menus are:
* Stand
* Min

An example of a mega menu that is managed via a module:
* Oli

# Detailed design

### Creating a mega menu in the sitemap

I'm thinking we have a `megamenu_navitem` that we can add to the sitemap that groups nodes, similar to how a folder or a module navitem would. This megamenu navitem would house all sorts of content that the user can customise.

![mega-menu-sitemap-simple](https://cloud.githubusercontent.com/assets/685024/23978924/71c173c0-0a46-11e7-98b5-f47a65c4ba7b.PNG)

(it would obviously not look like a module, but instead have a really cool icon that totally makes sense and illustrates exactly what a megamenu is, like a speedboat 🚤, or maybe a christmas tree 🎄)

Editing a mega menu would show all the options that we have set for mega menus in this application:

![mega-menu-edit](https://cloud.githubusercontent.com/assets/685024/23979580/51eaafcc-0a4a-11e7-90fe-382f9a6a58c2.PNG)

### Back-end configuration

The main issue here is that the megamenu_navitem model will almost always need to be customised. 
Not all our sites will need megamenu_navitems so I don't think it should be generated in to the project by default, nor do I think Koi should even have one by default, or atleast one that gets used. It might have a template for one if possible, or maybe a file outside of the regular models that gets generated in to the project when we ask it to be. 

I'm thinking that if a megamenu_navitem model exists in the project that the mega menu options get exposed to the sitemap. This allows us to build our mega menu model in the application and only have Koi react to it rather than having Koi dictate our mega menu. If there's no megamenu_navitem model, no mega menu options should appear in Koi. 

Alternatively, rather than checking if the model exists, we could make it a Koi configuration to enable/disable mega menu support in the sitemap. Something like `Koi::Sitemap::MegaMenus = true`

We could set up a generator for it though that acts just like `koi:admin_controller` does for feeding the fields in to it:

```
rails generate koi:megamenu_navitem title:string description:text image_id:integer show_descriptions:boolean
```

### Front-end configuration

Having a special navitem type allows me to customise the simple_navigation renderer to only attach the mega menu behaviour to parents of mega menus. 

The current method is done by hard-coding the navitem `id`s in CSS/JS, which is obviously an issue when going from dev to staging to prod since the ids will often be different. This is not ideal. 

The biggest issue I see is what if the user decides they are going to add a mega menu to the footer navigtation? Or somewhere where the front-end simply has no implementation for a mega menu. 
To combat this, I think the default `sf_menu` renderer will need to be updated to simply pass-through the mega menu items. They will still act as nested items under the main item, but instead be treated as level 2, rather than level 3. 
The `sf_menu` renderer is quite abstracted and confusing so it might even be simpler to create our own new default renderer. 

Then we'd create a second out-of-the-box renderer for mega menus and use that on the front-end where we specifically want mega menus to be available. 

### Impact on other navitem types

We would need to over-ride the navitem model in the project if we're doing things like adding images or short descriptions in mega menus for each link. 

# Drawbacks

Only one in a dozen sites have mega menus. The hacky method works but lacks extensability. 

# Alternatives

Another option to extend on the mega menu container navitem is to create another megamenu column grouping to let the user manage the columns themselves, rather than splitting them and calculating them in the view. 

This could lead to inconsistencies we probably don't want though, like some mega menus only having one column, some having three, maybe one that has five. 

Something like this:

![mega-menu-sitemap](https://cloud.githubusercontent.com/assets/685024/23978872/3322508a-0a46-11e7-8290-2b12443aa0ed.PNG)

Another alternative I considered was instead of creating a new navitem type we could just take advantage of the folder type. Maybe folder types could get a new checkbox `is_megamenu` that when checked exposes the mega menu options via *show.js*, or push the settings to a new tab or something.  

An even simpler option is instead adding `is_megamenu` to all navitem types. This saves the extra middle-man node, but could be weird if we can all of a sudden see these settings anywhere in the sitemap. 
Having a middle-man node makes it easy to visualise what is a mega menu and what isn't. 
This could be solved by adding another icon to the parent node or something along with the hidden and key icons.

# Unresolved questions

What happens when the user inevitably adds a regular navitem at the same level as a mega menu container? 
Should we somehow prevent them from doing this, whether it's a rails validation or JS behaviours to check where they are dropping things? 

I'm open to any other suggestions. I feel like I may be over-engineering this. 
While writing up the alternatives I think the last alternative actually makes a lot of sense and could be easier.

**Comment by Obversity** [comment]
I don't feel like I know enough about the topic to comment, but I do seem to recall it being difficult each time we do it, yeah. Having a solution in koi would let us suggest megamenus more readily, when we think they make sense, as well.

**Comment by jsidoryn** [comment]
@dbaines great RFC. not a lot of comment as it's likely something that mainly affects you. would be great to have a solid approach to these though and these options seem like a good way to tackle. i reckon this is plenty for this RFC as it's likely to be lower down on the list. lots of good thinking there when we do get to it.
