### ISSUE TITLE
Subsite Processes

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#298]
- Start Date: 2017-03-16
- Owner: DB
- RFC PR: 

# Summary

This isn't so much a request for a new feature, but more of a discussion of our internal processes. 
How can we better manage subsites? Is there anything we can improve? Are we just amazing at them and we don't need to do anything? 

# Motivation

We've done subsites a few times now. We're probably going to do a subsite again in the future at some point. What have we learned? Is there anything in Koi that could make our life easier for next time? From Koi configuration, to front-end build process, is there anything we can improve or create guides for? 

# Detailed design

### Asset configuration

Having done a few subsites now I've got asset configuration pretty down-pat. 

Generally, Ornament stylesheets for example are set up like so:

```
assets
-- stylesheets
---- components/_component.scss
---- utilities/_utility.scss
---- application.scss
```

For applications with many sites though, I move to a system like this:

```
assets
-- stylesheets
---- mysite
------ components/_component.scss
------ utilities/_utility.scss
------ mysite.scss
---- subsite
------ components/_component.scss
------ utilities/_utility.scss
------ subsite.scss
```

This works really nicely and you can even mix and match components and utilities and such as required.
For example the `mysite/components/comments.scss` might be used by all subsites because it's pretty generic. But subsite7 has it's own comments component because it's just heaps different,  `subsite7/components/comments.scss`

Later on, subsite3 might see subsite7's comments style and think, 'hey that would look really good on subsite3', so subsite3's stylesheet could be updated to use subsite7's comments.scss instead of the default mysite one:

```scss
/* app/assets/stylesheets/subsite3/subsite3.scss */
...
@import "../mysite/components/shared-component1";
@import "../mysite/components/shared-component2";
@import "../subsite7/components/comments";
@import "components/subsite3-specific-component";
...
```

Likewise, subsite5 could introduce a new feature like FAQs that no other subsite has had before, but any other subsite could pick up the styles for it by adding `@import ../subsite5/faqs` and boom! They suddenly have FAQ styles. 

This has worked nicely in the past and I don't see any immediate issues with it. Currently I've only done it for stylesheets but the same structure could be applied to javascript if needed. 

### Layouts/Templating

Depending on the complexity of the subsite, we've created templates for each subsite, like so:

```
layouts
-- subsite1/application.html.erb
-- subsite2/application.html.erb
-- application.html.erb
pages
-- show.html.erb
subsite1
-- pages
---- show.html.erb
```

Another method we've done in the past is to create a middle-man application layout that feeds configuration to the main application template. This works really well when there's only minor templates differences:

```ruby
# app/views/layouts/subsite1.html.erb
<%-
  content_for(:homepage_url,"/subsite1/")
  content_for(:logo_url, "/assets/subsite1/logo.svg")
  content_for(:fallback_title, "Subsite 1")
-%>
<%= render :file => "layouts/application" %>
```

These methods work pretty well, I've found. 
I can't really think of anything that would make life easier here. 

### Routes

This is probably a big one. On YSA for example I know you can access subsite pages on the main site and vice-versa and see the same content in a different template. 

We would need a method of scoping page routes to subsites and not having them bleed through to subsites or back to the main site. 

### Multiple sitemaps

This is a big one and has its own RFC, right here: https://github.com/katalyst/koi/issues/296

### Asset manager

Do we need a way to scope asset manager files to subsites? Asset manager has tagging so it could be as simple as keeping it front-of-mind to tag assets to the subsite, and educating the client on this. 

### Admin management

If an admin is only an admin for a subsite, should they only see options for that subsite? 
Should we lock them in to a scoped version of Koi that only exposes them to stuff for them? 
What about users that are admins for all subsites? 
There might be something here, this could even be its own RFC around scoping admin users or possibly even expanding roles. 

The Oli method of splitting countries in to their own scoped dashboard worked out really well. 

# Unresolved questions

Is there anything anyone else can think of that might need improving here? 
Is there anything we should be discussing regarding hosting or domains? 
Should we be documenting the process of creating and managing subsites?

**Comment by Obversity** [comment]
RE Routes: I actually had a pretty simple solution to the problem of subsites having access to other subsites / the main site's content in YourSAy, but it required a major refactoring of the routes file and it never got deployed to production for whatever reason. (Basically all the main site's routes needs to live inside a scope themselves. I'm not sure why it didn't occur to me when we did the first subsite—CNC.)

**Comment by Obversity** [comment]
I'm not completely sold on putting anything directly in koi to deal with this because (a) it's not super common, (b) the requirements for administration of these subsites is often quite different, and (b) it'd be a bunch of added complexity. 

I definitely think there's value in documenting how we've gone about building subsites in the past, though, and what the learnings from it were. We've definitely gotten more efficient at it.
