### ISSUE TITLE
Rich Text Editor - Basic Variation

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#299]
- Start Date: 2017-03-20
- Owner: DB
- RFC PR: (leave this empty)

# Summary

Provide a basic variation of CKEditor with stripped down options.

# Motivation

This came out of https://github.com/katalyst/koi/issues/249
Sometimes we have fields that should have bold, italic etc, but shouldn't have images or tables or other stuff.

# Detailed design

There are two ways I can see us doing this:

### 1. Custom field types

This could be a new field type, like:

```ruby
crud.config do
  fields short_description: { type: :rich_text_basic }
end
```

### 2. Predefined configuration option

It could be a configuration option passed in to the type:

```ruby
crud.config do
  fields short_description: { type: :rich_text, toolbar: :basic }
end
```

Or we could maintain a list of configurations and pass those in to the crud config:

```ruby
#config/initializers/koi.rb
Koi::RichText.basic = [['Source','-','Bold','Italic']]
Koi::RichText.faqs = [['Bold']]

# app/models/mymodel.rb
crud.config do
  fields short_description: { type: :rich_text, toolbar: "basic" },
         faq_description:   { type: :rich_text, toolbar: "faqs" }
end
```

### 3. Configurable CKEditor in Model

Another option is to have it entirely configurable in the crud config:

```ruby
crud.config do
  fields short_description: { type: :rich_text, toolbar: [[ 'Source', '-', 'Bold', 'Italic' ]] }
end
```

This is more configurable but we would need to reproduce the config each time we implement a "basic" version. If they all end up being the same this could be a pain to maintain. 

For reference, here is the current toolbar in Koi:

![screen shot 2017-03-20 at 1 08 33 pm](https://cloud.githubusercontent.com/assets/685024/24087403/6457eb4e-0d6e-11e7-98c6-21f1b5f1234d.png)

# Drawbacks

If we lock in the "basic" buttons now we might end up stuck with settings we don't like. 

# Alternatives

This hasn't really come up as a requirement before, so we could just leave it. 

# Unresolved questions

Which method does everyone like? 
Any opinions on what a default "basic" editor should have?

**Comment by Obversity** [comment]
Definitely sounds good to me! I like option 2, where you can configure more toolbars for when you need them, and they can easily be reused. 

I'm thinking we'd want a few default ones configured when you bootstrap Koi.  Maybe a basic one as you've used above, and maybe a basic + links one as well.

**Comment by jsidoryn** [comment]
I think we can could make the default much simpler. 

Remove the different paste options and just keep paste as plain text (do we trust paste as word?)
Remove search
Remove the b -> a thing (don't even know what it does?)
Not sure what the paragraph thing next to it is for?
What's the one top right? Remove? 
Remove underline
Remove indenting - and maybe add one for 'block quotes'
Remove table

I think if we had something stripped back as default and then a 'full' one as an option that might work.

**Comment by Obversity** [comment]
> don't even know what it does?

@jsidoryn You can mouseover the icons to work out what they do.

**Comment by dbaines** [comment]
@jsidoryn 

I definitely don't think we should make the default simpler. We will be forever adding them back in for clients that need/want them. 

I'm strongly opposed to stripping these things out:

* Paste options from word (not relevant what we use it for, we don't use it, the client does)
* Search and replace (has been requested several times)
* Top right is show blocks so you can see the elements in editor (eg. the huge space at the bottom is caused by ten empty paragraphs)
* There is no underline, that's strip formatting which removes any renegade inline styling which clients have no way of removing unless they go in to the source (eww)
* Indenting (nested lists need to be a feature)

Blockquote is available under "Format". I've never seen a client use one and we definitely don't support it on the front-end of our sites anyway. 

For reference, here is the CKEditor interface: http://sdk.ckeditor.com/samples/fullpreset.html
If you don't know what they are you can hover over the icon to see the label.

**Comment by Obversity** [comment]
I definitely agree with Dave here. I'd rather have a default with lots of options that we can very easily strip back, than have a default with few options that we have to remember to add more options when we guess that the client might want it. 

This would be different if these options were a performance problem, slowing the editor down or something. But they don't seem to be, or at least not significantly, even with lots of editors on the page.

**Comment by jsidoryn** [comment]
@dbaines @Obversity i think we all agree that we are trying to work out the default that covers 90% of cases, not a minimal set just for the sake of it. 

thanks for the feedback @dbaines, you've got a much better feeling for the needs of the clients then I do. happy to go with your recommendations.
