### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#300]
- Start Date: 2017-03-21
- Owner: DB
- RFC PR: (leave this empty)

# Summary

Show breadcrumbs in the Koi UI

# Motivation

Sometimes it's easy to get lost in Koi. 
Especially with deep nested modules. 

# Detailed design

![screen shot 2017-03-21 at 9 19 41 am](https://cloud.githubusercontent.com/assets/685024/24125245/b211aa56-0e17-11e7-8ba6-d244a31107cd.png)

```ruby
<% content_for :breadcrumbs do %>
  <a href="#">Modules</a> › <a href="#">Heroes</a> › <span>Super Heroes</span>
<% end %>
```

# Drawbacks

Breadcrumbs are always hard. Even on the front-end we've resorted to hard-coded methods of breadcrumbing. 

Could be hard to build a "just works" system for it due to nested modules and stuff. 

# Alternatives

If we can't build a "just works" system, we could at least expose a method in the crud config for populating breadcrumbs. Or create a dynamic partial in `/admin/<module name>/_breadcrumbs.html.erb` that gets loaded in if found.
This could create an inconsistent experience though and would need to be properly maintained. 

# Unresolved questions

How can we do it?

**Comment by Obversity** [comment]
I agree, there's pretty obvious up front value in breadcrumbs. And yup, the real question is how we can actually do it, without having to re-architect the whole thing, lol. I'll give it some thought!

**Comment by Obversity** [comment]
1. We don't have a listing page for 'modules'. Would we want modules as a link in the breadcrumbs? Should that be the dashboard, maybe?
1. Would we want it to include nested resources?

    I.e. if you're at the route 

    `admin/discussions/make-koi-great-again/comments/i-think-its-pretty-cool`

    Would we want the breadcrumbs to include the discussion?

    i.e.

    `Modules > Discussions > Make Koi Gre... > Comments > I think it's...`

We can do nested resources at least one level deep, but after that it'd be a bit more work. E.g. for the route

`admin/decisions/is-koi-good/discussions/make-koi-great-again/comments/i-think-its-pretty-cool`

We could do 

`Modules > Decisions > Discussions > Make Koi Gre... > Comments > I think it's...`

But we'd need to do some tricky stuff to make 

`Modules > Decisions > Is koi good? > Discussions > Make Koi Gre... > Comments > I think it's...`

Work properly. It's probably doable though!

**Comment by jsidoryn** [comment]
My preference is to make a more powerful search as you've already started doing @dbaines in the nav search. If this was a spotlight type feature then this would become less important. 

I'm not sure if this is something I want because it's how I search already. Clients who may be more point and click may value bread crumbs much more. 

When they are deeply nested it becomes a bit messy in the UI. Maybe it could be limited to 3 levels or even just a back button at the top of the page as that's likely to be the most used link? 

From past experience it seems that it would need to be hand crafted for it to work best and this may be an overhead that's too much for the value.

**Comment by Obversity** [comment]
I don't see Breadcrumbs and Search as being all that related. 

For example, if I'm viewing a comment at the url

`admin/discussions/make-koi-great-again/comments/i-think-its-pretty-cool`

And for some reason I want to go back and view details about the discussion (i.e. I want to go to the url `admin/discussions/make-koi-great-again/`) then a koi module search isn't going to help me at all, but Breadcrumbs will.

**Comment by dbaines** [comment]
@jsidoryn 

Yep I agree with Bill. Breadcrumbs aren't search and I personally think it's even more valuable than not when you're deeply nested. It's about knowing where you are not about navigating somewhere else.
