### ISSUE TITLE
Long index actions list

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#301]
- Start Date: 2017-03-21
- Owner: DB
- RFC PR: (leave this empty)

# Summary

Provide (possibly optionally) a nicer interface for actions in listing table.

# Motivation

Sometimes the index listing table gets pretty chockers full of actions:

![screen shot 2017-03-21 at 10 50 48 am](https://cloud.githubusercontent.com/assets/685024/24127422/6e55fe7c-0e24-11e7-8856-cf467c89bb26.png)

# Detailed design

Currently the actions area is filled with a few things:

1. Links to viewing the record: Edit, Show 
1. Relations: Related index listings for nested modules  
1. Custom actions: Either hardcoded HTML links or via the `_custom_index_fields_actions` partial  

I've seen long actions handled via select menu or a drop-down list of links in the past, something like this:

![screen shot 2017-03-21 at 10 59 05 am short](https://cloud.githubusercontent.com/assets/685024/24127997/e4c3f2ae-0e28-11e7-9233-66ac7013b11a.png)

Or maybe a toggle menu like this:

![screen shot 2017-03-21 at 11 16 06 am](https://cloud.githubusercontent.com/assets/685024/24127864/db4c8a2a-0e27-11e7-8c3f-87366c7300fb.png) 

I personally prefer the select menu approach since it will be a better experience on mobile and scales up with a browser control rather than something we need to worry about on the front-end. 

# Drawbacks

Could have negative impacts with batch/spreadsheet editing if that feature ends up being in the same interface.

Might look a bit silly if 90% of the models only have an edit link. We could measure the action count before render and then show either a select menu or a list of links depending on how many there are. Lets say more than 3 gets the "long" treatment. 

# Alternatives

I've provided two options, I'm happy to hear others. 

# Unresolved questions

Do we need to split or categorise the links in any way? For example, the nested modules aren't really "actions", do we identify them or label them differently?

**Comment by Obversity** [comment]
It'd be good to see what other content management systems do for this. I like the idea of an 'actions' menu, but I agree that it's weird that most of them are in fact relationships (i.e. nested modules) not actions. A select menu / dropdown could work, though!

**Comment by jsidoryn** [comment]
Definitely needs better solution. 

I quite like overlays for this kind of thing. So a full screen overlay with big buttons that are easy to press. This works nicely on mobile as there's a bit tap zone and I'd argue is just as usable on desktop. In some ways more useable as your focus is drawn to the single task at hand.

**Comment by Obversity** [comment]
I'm not sure I understand your proposal, @jsidoryn. Would you click a button (maybe titled "actions"), then it'd come up with a modal with links to the actions / relationships in it? 

If that's what you're suggesting, it seems like overkill to me, and not great UX in my opinion, since on desktop, you'd have to move your mouse *way* further than you currently do. Do you have an example of an UI that uses anything like this?
