### ISSUE TITLE
Pagination doesn't indicate there are more pages

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#307]
- Start Date: 2017-03-28
- Owner: DB

# Summary

Pagination doesn't indicate that there are more than 5 pages.

# Steps to reproduce

1. Find a model with more than 5 pages of records
1. Click on page 5

# Expected results

I expect page 5 is the last page

# Actual results

There are actually more pages

# Additional notes

Should be an easy fix, Kaminari has "gap" elements that you can render when there are more pages, eg:

```
1 2 3 ... 15
```

The most complex version would look something like this:

```
1 ... 5 6 7 8 9 ... 15
```

This tells the user there are more pages available and shows the first / last page as a reference. 

This does not affect mobile version.

**Comment by Obversity** [comment]
@dbaines 

Nice find! I witnessed this on Fringe the other day with competition entries. 26k records in the database, but only showing page buttons up to 5. Didn't think much of it until I read this.

**Comment by jsidoryn** [comment]
@dbaines feel free to close this if done :)
