### ISSUE TITLE
Implement Role based config for users

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#311]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

*Provide ability to implement role based user security.*

*When a system requires multiple user types(roles), it would be useful to standardise how we implement this type of feature.
Generally a gem like cancan is used to provide a simple yet effective way to ensure a users role should have access to certain functionality within the application.

This could also be extended to users of the admin interface in KOI. We currently have admin and super admin.
*

# Motivation

*Adding roles to users in an application provides finer grained access control to specific features within an application. (A simple example would be registered user access versus non registered users.)*

*By adding a standard interface for managing user access roles, this makes it easier for all team members to understand the implementation. Adopting a standard industry way of managing roles also makes it easy for any new developer to the project to know how it works.*

# Detailed design

* As not all projects would require user roles, but may become a requirement later in the applications life, it would be useful to add a generator that would hook up the plumbing for a standard implementation. *

*A standard implementation would be to add the required gems to the project and hook it up to either the existing user functionality or add the user functionality where a project has no users currently. It could also be an option in the initial bootstrap process , i.e. --with-user-roles*

# Drawbacks

*The main drawback with this would be that it would lock our application into using a specific method of role based security. This may not be so bad and if architected correctly, could be easily swapped out if a better way is discovered.*

# Alternatives

*Without a role based system, where required, code can become spaghetti like very quickly when work around are added to implement similar functionality.*

*This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.*

# Unresolved questions

*Would cancan be the best method of implementing roles, or is there a better system available?*

**Comment by Obversity** [comment]
> Would cancan be the best method of implementing roles

Pundit has been a pretty popular alternative for a while. I used it in the YourSAy API and it was pretty easy to work with in that context. That said, my use of it was pretty limited, and cancancan wasn't too difficult to work with on the few times I've had to touch med. 

>  ...it would lock our application into using a specific method of role based security

As you mention, this might not be such a bad thing, as long as we make it reasonably flexible and architect it well. 

> code can become spaghetti like very quickly

Agreed! Having a go-to tool for authorization even when we don't have complex roles might be good. We usually seem to roll our own, and it's usually pretty flakey and all-over-the-place, between apps. 

> generators

I think for the Users functionality we agreed that it should be a generator rather than a bootstrap flag, so I think a generator would be the way to go here as well.

**Comment by jsidoryn** [comment]
I've seen a lot of love for Pundit also more recently. Probably between either pundit or cancancan.

@pvawser01 what do you see being generated? I would expect that roles are very specific to the project and so little could be generated. Or are you thinking include the addition of the gem to the gemfile when generating a user on the front end?

**Comment by pvawser01** [comment]
@jsidoryn I haven't used Pundit. However, I see a generator adding required gems and in the case of cancancan, it could create a base ability file with some sensible defaults. It could even be more useful if you pass it a list of roles it could create the appropriate convenience methods for roles in the ability file. Basically create a default structure that would, I guess initially give all roles the same access all. This could then easily be restricted base on business rules. Generate any boilerplate code.
