### ISSUE TITLE
Add test templates to KOI generators

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#312]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

*KOI already has generators to create models, controllers and such. However, automated tests (feature tests and or unit tests) are something that is ignored. Extending the current generators to also add test templates might be a good way for us to start building mor robust application by utilising the benefits of automated test.*

# Motivation

*Automated tests are one area where we in general, well... suck at. It is proven that automated tests aid in the development and extending of systems and more so as a system become more complex.*

*By having the KOI generators create test templates for newly created objects, might encourage developers to write tests as we develop functionality to ensure business rules are not broken by later development.*

*While the industry does document the benefits of TDD not all developers work in that way. BUt even a test written after the code has been written is a good test.*

*It would need to be agreed upon as to a minimum required level of testing but it would make code bases more robust and improve the general developer skills.*

*Tests, if done right can also be a form of documenting business logic, that can be forgotten after time passes on a project.

# Detailed design

*Make KOI generators create test templates for the object being generated. depending on the test framework utilised, it might be beneficial to create a simple DSL for test. This is especially useful when using rspec for functional tests.*

# Drawbacks

*Will initially add time to the development process. However, it can be a selling point, being the additional value add we provide.*

# Alternatives

*Continue the way we have been.*

# Unresolved questions

*What test framework would we want to adopt? How should we ensure a minimum standard is being adhered to? All options need to be as efficient as possible.*

**Comment by Obversity** [comment]
> Automated tests are one area we suck at

It's definitely not my forte, yup. What testing framework are you most familiar with? I'd suggest we go with that, so at least the initial hurdle of setting it all setup won't be too tricky, and you'll be able to school me in the various types of tests you think are worth doing. 

I've done a tiny bit of testing in Rspec but I'm not at all attached to it.

**Comment by pvawser01** [comment]
I'm guilty also. Personally I like minitest as you don't introduce new gems as it's already in rails. That said rspec reads better with cucumber. The problem I have found in the past is people start writting their own dsl for things and you end up with 10 different ways to describe clicking a button. It would be good to define a simple common language for tests and just use those. At the end of the day a click of a named button is the same no matter how you word it. Also makes it easier in describing the functionality through cucumber at the scoping pahse.
