### ISSUE TITLE
generator for Image/video gallery

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#313]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

*Add generator for add in generic gallery functionality to an existing model.*

# Motivation

*We seem to regularly have the need to add gallery functionality to applications. While not so difficult to implement, it is boiler plate code that could be added as a generator , thus allowing devs to spend time on business logic rather than boiler plate code.*

# Detailed design

*Bill has previously created a nice galleryable concern that works very well and is simple to implement. Recently I modified it for a project to also handle movies (youtube clips). We could add this to a koi generator to add to project when required and hook it up to a model (DB migrations, includes in models, even a view helper method that can be easily dropped into a view as required).*

example:
https://southerncrosscare.com.au/locations/riverside-retirement-living

# Drawbacks

*As this would be a default implementation, it could always be modified as required. No real drawbacks that I can see.*

# Alternatives

*The implementation Bill has built is pretty well built, so I don't see a need for alternatives at this stage. It is a common requirement and we solve all in a similar way.*

# Unresolved questions

*???*

**Comment by Obversity** [comment]
Sounds great. 😄  

> even a view helper method

I'm not sure the markup would always be the same, so that's probably up to @dbaines.

**Comment by dbaines** [comment]
The markup would probably change project-to-project but having one generated isn't a bad thing.

**Comment by jsidoryn** [comment]
sounds good. @pvawser01 could you add some links in the above write up to example of galleries we've built in the past.
