### ISSUE TITLE
generator for basic checkout and cart functionality

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#314]
- Start Date: 2017-03-04
- Owner: PV
- RFC PR: 

# Summary

*Having a standard approach to shopping cart functionality (backend) would be useful in saving time in the setup and implementation of common functionality that most all carts/checkouts have.*

# Motivation

*Since starting at Katalyst, I have been involved with implementing about 3 or 4 shopping carts.*
*While some have very specific workflows, they are generally implemented in a very similar way.
It could be beneficial to have a generator that could build the bulk of the implementation and hookup, to save reinventing the wheel.*

# Detailed design

*We have always created custom carts and checkout functionality. However, most have been implemented with the same basic structure/workflow.*
*Having a standard approach to implementing ecommerce functionality would allow for faster build times and all team members would understand the flow and functionality across all projects.*
*The implementation could also have test within KOI, so out of the box, we can have confidence that base functionality works. It could then be customised to specific requirements.*

# Drawbacks

*As it would be a generator, if a projects requirements did not fit, we build from scratch. But if suitable, generate and within minutes we have robust ecommerce added. No real draw back.*

# Alternatives

*Alternatively, we could look at open source or hosted ecommerce functionality and utilise that as our base/goto ecommerce implementation.*

*This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.*

# Unresolved questions

*???*

**Comment by Obversity** [comment]
Is there enough commonality between the carts we've built to abstract much? 

I've only dealt with cart stuff peripherally with oliveri / fringe, usually on days when you're not available, so I can't really comment on this one, lol. I think you're the one who suffers the most from not having anything pre-built. 

Well, you, and our clients, when they have to foot the bill.

**Comment by pvawser01** [comment]
@Obversity enough said. If I'm suffering it's in. hehe.

**Comment by jsidoryn** [comment]
yep, my gut feel is that there's probably enough commonality that we could extract something useful. could also include integration with stripe out of the box.
