### ISSUE TITLE
pdf generation of data

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#316]
- Start Date: 2017-03-04
- Owner: PV
- RFC PR: 

# Summary

*Ability to export data in PDF format from KOI or even form front end.*

# Motivation

*Typically data is exported from applications, build by Katalyst as csv. While this is suitable for large number of records, there may be times where data would be better suited in some other format such as PDF. Reports for example*
*PDF's can be dynamically generated and attached to emails.*

# Detailed design

*PDF genration can be done very simply using tools like wicked PDF or prawn. It can be very useful where data in the database is required for documentation or reporting.*
*Adding a default way to build PDF's could save development time should this format be required.*

# Drawbacks

*Would lock us in to specific PDF generation tools.*
*May not be required often.*

# Alternatives

*??*

# Unresolved questions

*??*

**Comment by Obversity** [comment]
@pvawser01 Could you name a couple of cases where this has come up with a client, or maybe where it'd have been nice to be able to offer them a pdf export of something in Koi? 

> Reports for example

Yeah, pdf reports would be a pretty neat addition to any improved reporting tools we build. On the other hand, our usual graphing tools are javascript based, which in my experience don't play nicely with the PDF libraries available, so it could get tricky.

**Comment by pvawser01** [comment]
@Obversity Hasn't come up yet. It is more of a future direction thing. I've built plenty of things over my years that need to generate dynamic pdfs. It's just something we could consider.

**Comment by jsidoryn** [comment]
@pvawser01 are you thinking that this is something that should be built into koi in some way? I think we generate PDF's in Givematcher and I'm sure we've done it in other places. Or are you just suggesting that we research gems and create a process for this should the need arise?

**Comment by pvawser01** [comment]
@jsidoryn I was thinking that the basic plumbing for pdf generation could be built in, so that if a client did require PDf generation of data, some of the scaffolding could be generated in a standard way. No reason, you couldn't have functionality for this in KOI. Say for instance a client had has orders in KOI that get processed and the admin wants to send a PDF attachment of a generated Con note or receipt....

**Comment by Obversity** [comment]
@pvawser01 Was there anything in the recent YSA thing you did that'd be relevant here?
