### ISSUE TITLE
Profanity filtering as koi default implementation

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#318]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

*Profanity filtering would be good to have as a default for all applications. *

# Motivation

*As it seems that our standard implementation of this behaviour is the same from project to project, it seems fitting that it be implemented by default for all new projects.*

# Detailed design

*As part of the project template we could add the implementation of required code so that profanity filtering is available out of the box.*

*A generator might even be useful for adding to existing projects should they be upgraded*

# Drawbacks

*Profanity dictionary could become out of date relatively soon.*

# Alternatives

*?*

# Unresolved questions

*?*

**Comment by Obversity** [comment]
This might be good to have as a Concern that we can include where needed, e.g.

`has_crud filter_profanity: true`

I don't think we'd want to make it on-by-default though. You'd catch too many false positives. I'd rather let the occasional user submit a form with bad words in it than let the occasional user not submit their content because "summa cum laude" apparently contains bad words.

**Comment by pvawser01** [comment]
@Obversity Bahaha. I like your example. You've got a point though. I like the idea of it being a concern like that. Fits better with the KOI way I guess.

**Comment by jsidoryn** [comment]
@pvawser01 could you explain a bit more about how this would work. is this essentially a validation criteria so if someone submits a form it shows an error? or does it get submitted with the words removed or something else?

**Comment by Obversity** [comment]
@jsidoryn, YourSAy discussions have a profanity validation. Give it a shot on staging. There's at least one decision with an open discussion at the moment. 


Implementation wise, it might need to be something more like

`has_crud filter_profanity: [:field1, :field2]`

now that I think about it. Or we could validate for profanity on *all* string/text columns, I suppose.

**Comment by pvawser01** [comment]
@jsidoryn Like @Obversity mentioned. I guess I am suggesting a basic standard setup with sensible defaults. If there are specific requirements, we can customise the set up but at least the implementation boilerplate is done.

**Comment by jsidoryn** [comment]
@Obversity @pvawser01 thanks for that. i hadn't seen it in action and was just wondering how it was implemented.
