### ISSUE TITLE
Template to set projects as SSL by default

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#320]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

Modify KOI template to configure applications to use ssl by default.

# Motivation

Given the direction google are moving with regards to ssl. It would be a good idea to make all our apps ssl enabled by default.

# Detailed design

This really just means setting the application setting to force ssl. We would still need to ensure that ssl certs are purchased and installed. 

Currently, we use COMODO for ssl certificates. ON average it is several hundred dollars for a wildcard certificate.
It could be an idea to investigate the use of Lets Encrypt certificates, which are free and may allow us to add a cost effective solution for clients with tight budgets.

Another consideration would be regarding links that access http sites. If http urls are used in the https app, the browser will condier the site un trusted.

This also raises another issue with clients that want custom domains for s3 access. IN this case, the only real option is for them to pay for cloudfront. SNI works differently where, you use an AWS generates ssl cert and domain. Alternatively, you just use the s3 url with https and all is fine. ONly where clients insist on custom url's is the an issue. 

The use of cloudflare CDN is also an additional cost that the client would need to wear ($200 per month per domain).

# Drawbacks

The draw back with lets encrypt is that it does not allow wild card certs. You need to generate a cert for each sub domain. Also, you need in place cron jobs to renew certs regularly as they expire after 3 months. I have been using this on a personal app and it really is not that big a draw back. The COMODO certs I think do potentially allow for different locks in the address bar.

# Alternatives

*?*

# Unresolved questions

*?*

**Comment by Obversity** [comment]
Sounds like a great idea. 😄 

We might need to document our ssl purchase / setup process a little better though.

**Comment by pvawser01** [comment]
@Obversity Just not sure how well lets encrypt plays with Engineyard. It is just unix but if we stray too far from the EY way were asking for problems. With VPS hosts it becomes very doable.

**Comment by jsidoryn** [comment]
i think this one is a must. 

will be worth looking into lets encrypt, i know there are solutions for auto renewing before the 3 months are up. 

is not having wild card much of a problem? the main problem i see is if we have a multitenanted site that creates sub domains on the fly. in that case we could simply use something else. 

another issue that needs to be solved with this is the problem we were having with delivering s3 assets as is the problem with gymnastics australia.

**Comment by pvawser01** [comment]
@jsidoryn Not sure what this issue is?

> another issue that needs to be solved with this is the problem we were having with delivering s3 assets as is the problem with gymnastics australia.

**Comment by jsidoryn** [comment]
@pvawser01 that problem we have with ssl sites not showing the lock...

we were talking about using cloudflare and sni as ways to get around it

**Comment by pvawser01** [comment]
@jsidoryn I think that was YSA. That could be resolved by just using the https s3 url to assets. If clients want custom domains, then they need to be aware of additional costs. I think that is probably a project specific discussion and not really for this  RFC to debate.

**Comment by Obversity** [comment]
I agree with @pvawser01. If we go with S3 as the default setup for assets, https *isn't a problem* unless they require those assets to look like they're downloading from the same domain—in which case they need to pay for it. 

In 99% of cases, as the digital experts, we should be able to convince the client that it's not important for assets to look like they're downloading from the same domain.

**Comment by jsidoryn** [comment]
@Obversity paying for it isn't an option. asking someone to pay $7,200 USD each year for their assets to come from a sub domain is not an option. 

It is a problem for clients when they paste a link to a pdf and it doesn't look like it's coming from their site. This was important to YourSAy.

We may end up in the same place but I don't think we've properly examined the options. One of them being how important it is to clients (this is something Heath and I can do) but also what other options may exist.

**Comment by Obversity** [comment]
I'd argue that in most cases, they shouldn't be pasting raw urls, and should instead be creating links. 

I.e.

    [Click here to download this pdf](http://assets.yoursay.sa.gov.au/staging/2017/02/14/05/38/26/0fa279e1-330c-482a-9734-23c338fb929c/Test%20Pdf%204.pdf)

Rather than

    http://assets.yoursay.sa.gov.au/staging/2017/02/14/05/38/26/0fa279e1-330c-482a-9734-23c338fb929c/Test%20Pdf%204.pdf

And making people copy/paste it. 

And if they *really* do need to paste the url of an asset, they should create a URL rewrite for it, so the url looks nice, e.g. 

http://ysa-v2.staging.katalyst.com.au/puppy.jpg

Perhaps we need a  "create a nice url for this asset" feature in the asset manager, that creates a url rewrite for a particular asset.

**Comment by jsidoryn** [comment]
@Obversity rather than arguing one way or the other, i'd support exploring the options a bit further. heath and i will explore the needs of clients and it would also be good to better understand the other options and their implications

**Comment by jsidoryn** [comment]
General agreement that when using S3 and ssl it's ok to use the S3 url.
If this is a client concern in the future then we can tackle it then.
