### ISSUE TITLE
CI Server (Development tools/process)

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#322]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

Building a Continuous integration server to help improve delivery times of completed feature.
This works very well in conjunction with proper agile methodologies. ("Deploy early deploy often")

# Motivation

We have often found ourselves in situations where features that have been completed and are working are delayed for deployment. When we finally get to deploying them, we end up spending a lot of time on fixing merge conflicts, etc..
Also, with well defined tests, CI servers can help speed up the testing time thus helping in overall delivery time of new features.

# Detailed design

CI servers like Jenkins are relatively easy to set up. Once in place, projects can easily be added and configured with appropriate web hooks for automated feed back of a project state after a commit
A CI server could allow developers to move on to new feature while testing is done automaically by the CI server. If a commit breaks the "build" the team is notified and the developer responsible can look into the issue before it is deployed anywhere. This however must work in conjunction with sound testing methodologies. If the test harness is sub par or non existent, the CI server is useless.

CI servers can even be set to deploy to specific environments when build rules are passed.
This could help reduce bottle necks in the development lifecycle and improve the quality of code shipped to clients

# Drawbacks

Some additional cost and maintenance for projects
May require some up skilling of staff
A change in process and approach to project development.(Need to be more diciplined)

# Alternatives

There are hosted options such as travis but this costs more again and you still have the other internal issues to sort out first

This section could also include prior art, that is, how other frameworks in the same domain have solved this problem.

# Unresolved questions

*??*

**Comment by Obversity** [comment]
I'd be happy to trial this on a greenfield project, but yeah, we'd need to be very disciplined about testing from the start.

**Comment by pvawser01** [comment]
@Obversity  Yup!

**Comment by jsidoryn** [comment]
@pvawser01 definitely a key part of the stack but i think the trigger is 'when tests take too long to run'. at the moment i'm assuming that's not an issue and there might be another RFC around the writing of tests.
