### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#324]
- Start Date: 2017-04-02
- Owner: JS

# Summary

[Settings](https://github.com/katalyst/koi/wiki/Settings) needs a re-think from the ground up. 

# Motivation

Settings are getting used more and more. It's generally a catch-all place for collection-related data that has nowhere to live in the database. 

There are several issues with settings as they currently exist. 

From a development point of view:

* They are tied too much to the view. 
* The setting won't get generated until you view the page that the setting appears on. If the setting is generated by rails code, it won't be generated until whatever method it appears in is run (eg. "address" settings for mailers won't be generated until the first email is sent)
* If you change the name of the setting in Koi, you will need to rename it in the view so that it matches otherwise it will just generate with the old name again. 
* They are generated in the order that they are viewed on the front-end. There is no way to dictate the order or re-order them. 
* Global site settings have a completely different method of creation than model-based settings. We typically don't use site settings due to it's inconsistencies. 

From a user point of view: 

* They can often be considered too hidden and just generally confusing. 
* Settings can be stored against any model in any given view, so it's never really clear where the setting is going to be in the admin vs the front-end. 
* There's no centralised area for settings

# Detailed design

## Data structure 

It's been mentioned translations might not be the best place for it. 

## Creating Settings

Settings in the view are a big (but workable) problem. 
They will need to live in the code somewhere. When we deploy a new feature that uses settings we don't want to go in to Koi and create our settings manually. 
We ideally need some way of curating this list to change order, make on-the-fly naming/labelling changes. And of course they need to be editable in Koi. 

## Settings Explorer 

I think a way to explore settings would be very beneficial. Sometimes I know I and others will be looking around the admin for ages before we find the setting we're looking for. 

Some sort of interface where you can type to show filtered suggestions based on the name and value of the settings. 

## Seeded Site Settings

[Ornament now supports fallback title/description/keywords if they are set here](https://github.com/katalyst/ornament/blob/develop/lib/generators/ornament/templates/app/views/layouts/_seo.html.erb#L39-L45). Unfortunately Koi generates "Site Title" as it's default site title setting. It would be nicer if this generated an empty value so it's not used unless it's filled out. 

Do we need a seed button? If the seeds aren't run there will be no admins. If there are no admins you can't log in to Koi. If you can't log in to Koi you can't press the seed button. I think it would be a very specific situation you would be in to warrant a seed settings button. 

We should look at the default settings it generates. Especially around Google Analytics. 
We don't need Analytics Username/Password fields or an embed version of Google Analytics. These currently have default values for the admin@katalyst.com.au account. Luckily the username/password combo doesn't work. 
The Profile ID is good to have, and Ornament now generates Google Analytics code off of this field. It would be nice if it was empty by default though. I have no idea what property UA-2161859-1 is, but it probably shouldn't be generated in to all our projects. 
The "Show Google Analytics" setting is a bit excessive. We can determine if it should be shown if the Profile ID field is filled out. 

# Drawbacks

Changing settings in such a drastic way will upset the upgrade path. 

# Alternatives

Translations, migrations, singletons or some other method I haven't thought of. 

# Unresolved questions

Methods, best practices, upgrades, UI...
Implementation as a whole, really.

**Comment by dbaines** [comment]
FYI I've created a pull request with some better default settings:
https://github.com/katalyst/koi/pull/325

**Comment by Obversity** [comment]
So I've noticed that we can actually declare settings in the model if we want to

```ruby
class SuperHero
 
    setting :something, "This is a value", field_type: :text, role: "Admin"
    setting :something_else, "This is another value", field_type: :rich_text, role: "Admin"
    # etc

end
```

There's still no way currently to reorder these, but we could probably modify the `setting` method to maintain a list of the settings its generated for a model, which we could then use on the front-end to order them nicely, as per the order they were declared in the model.

**Comment by jsidoryn** [comment]
All looks good and agree brining it out of the view is good. Does anyone have any thoughts on how this could work from a UI perspective? Also with the current implementation of setting in model, can you specify if this is for collection or member?

Are you thinking a page in the admin for settings and then each page can be found there with settings. Or would it be similar to how it is now with settings as a tab on the collection or member. 

Another option might be that when logged in as admin, if you are on the front end and hover over and click it will take you directly to the edit page in admin. I think @Obversity may have mentioned this idea elsewhere and I think we did a similar interface for SCC?

**Comment by Obversity** [comment]
> if you are on the front end and hover over

**Comment by Obversity** [comment]
>  if you are on the front end and hover over

Yup, we did something similar for Stand, but doing it for individual settings would be tricky. It needs a url to go to, and at the moment, there isn't a url for individual settings (I think I just made it go to the settings tab for Stand).

>  can you specify if this is for collection or member?

These are just collection settings. I don't think we ever use per-member settings for anything other than SEO. In 99% of cases, if you want some information stored against a record, you just add a field to the table. 

I suppose you could use per-member settings if you wanted to be able to add it to *any* model without having to worry about adding a column. So, for example, the 'composable_data' field needed by the Composable concern that Dave's working on could probably be implemented as a setting. (The downside to this is that it'd make building search features on top of it a lot more difficult.)

**Comment by dbaines** [comment]
> from a UI perspective

### Settings section

If we're putting all settings in to a single interface, we could seperate out setting pages using the already existing tabs:

![screen shot 2017-04-04 at 4 21 28 pm](https://cloud.githubusercontent.com/assets/685024/24644462/d72c679a-1952-11e7-95ff-5c14aeecc795.png)

This would make searching between main site settings and module settings a bit weird as they wouldn't all be present on the page at the same time. 

Or we can just run them all as seperate tables one after each other:

![screen shot 2017-04-04 at 4 23 31 pm](https://cloud.githubusercontent.com/assets/685024/24644511/1e029ee6-1953-11e7-83ef-015d0dd6ccba.png)

Running them all in the one view would be easier for searching etc. 
We could plonk a search field at the top of the page and do a simple javascript filtering on keypress, similar to how the menu filtering works. 

I think having them in tables at all is a bit weird and if we're going all out, we could have a crazy settings page like this:

![settings](https://cloud.githubusercontent.com/assets/685024/24645092/e0d2de20-1955-11e7-9ef3-f8322f1a8a26.jpg)

### Module settings

I think it would be nice to retain the module settings in the module area somewhere. Even if it's just a link that appears when there are settings present. It could link to the settings page and anchor down to the appropriate module.

**Comment by dbaines** [comment]
[Version 2.3.5](https://github.com/katalyst/koi/releases/tag/v2.3.5) release includes a quick bandaid fix for Site Settings by implementing an inline form like how module/collection settings works: 

![screen shot 2017-09-01 at 12 51 30 pm](https://user-images.githubusercontent.com/685024/29954254-95faf4b0-8f15-11e7-8ca5-6a4e826d93d0.png)

The regular old settings configuration is available under the "Configure" tab, where you can create and alter the field values for settings.
