### ISSUE TITLE
Nicer fallback for untitled records

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#326]
- Start Date: 2017-04-02
- Owner: TBA

# Summary

Create a smarter fallback for records that can't determine a title:

![screen shot 2017-04-03 at 5 39 17 pm](https://cloud.githubusercontent.com/assets/685024/24600597/88edc66e-1894-11e7-8a0b-4a39692138b0.png)

# Steps to reproduce

Don't add a `to_s` method on a model, or [define a fallback title in the crud_config](https://github.com/katalyst/koi/wiki/Crud-Config#page-titles)

# Expected results

In the example above it would be nice if it attempted to create a human friendly word from the model name, eg. Comment. 

# Actual results

![screen shot 2017-04-03 at 5 39 17 pm](https://cloud.githubusercontent.com/assets/685024/24600597/88edc66e-1894-11e7-8a0b-4a39692138b0.png)

# Additional notes

This can be combated manually by making sure we always specify titles.

**Comment by Obversity** [comment]
I think a better solution would be for the generators to add a default `to_s` method, with something like

```ruby
# lib/generators/koi/mailer/templates/model_template.rb
...

def to_s
  <% if @model_attributes.any?{ |attr| attr.name == "title" || attr.name == "name" } %>
    title
  <% else %>
    <% class_name %>
  <% end %>
end

...
```

`to_s` methods are useful for all sorts of reasons and IMO most models should implement one. 

Disclaimer: I haven't tested the above, but I think you get the gist.
