### ISSUE TITLE
Alternate display for white images

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#327]
- Start Date: 2017-04-04
- Owner: DB

# Summary

Provide an alternate view for white images, rather than showing the white image on a white background. 

# Motivation

When someone uploads a purely white image (eg. a white logo) you can't see it since it gets shown on a white background. 

![screen shot 2017-04-04 at 9 43 55 am](https://cloud.githubusercontent.com/assets/685024/24636695/48bb6506-191b-11e7-8870-48b0a2520c5d.png)

# Detailed design

This also affects the inline image uploader as that also puts the image on a white background. 

From what I can see, these are our available options:

### 1. Put a dark background on all images:

![screen shot 2017-04-04 at 9 48 40 am](https://cloud.githubusercontent.com/assets/685024/24636802/e979f6b0-191b-11e7-98a4-89b7b8dd891f.png)

This has the same problem in reverse. If a user uploads a black logo, it's now invisible. 

### 2. Put a medium-grey on the background:

![screen shot 2017-04-04 at 9 49 54 am](https://cloud.githubusercontent.com/assets/685024/24636830/16dd2172-191c-11e7-87d3-2724346a843e.png)

This will solve white and black logo images, but will be problematic in the (unlikely) event that we need medium-grey images. 

### 3. Do something smarter

If we go ahead with #280, we could look at the dominant colour of the image and get the opposite colour and put that on the background. 

# Drawbacks

Could be even more confusing to the user. Is this black part of the image? Has it added a background to my image? 

# Alternatives

I tried a photoshop-style checkerboard to the background but didn't really like it: 

![screen shot 2017-04-04 at 10 01 05 am](https://cloud.githubusercontent.com/assets/685024/24637107/bb400184-191d-11e7-8c5e-fc4135ebee7a.png)

Maybe it's fine as-is. It's a white image on a white background. Most people are clever enough to realise what's happening there. 

You can tell that there is actually an image there as it doesn't show the fallback image when there is no image: 

![screen shot 2017-04-04 at 9 53 43 am](https://cloud.githubusercontent.com/assets/685024/24636914/9d7ef7be-191c-11e7-9d94-8c51cc81000a.png)

# Unresolved questions

Is this a big deal? How much effort do we want to put in to this? I think it's a pretty low-gain issue.

**Comment by Obversity** [comment]
I reckon a grey background is probably the best, cheapest, least confusing option. 

>  I think it's a pretty low-gain issue.

Yeah, I don't think it's something we'd want to spend heaps of time on, heh.

**Comment by jsidoryn** [comment]
I don't think it can be black as same issue if black text. 

Grey has the least chance of clashing and as low priority and low effort might just be worth going ahead with it.

**Comment by dbaines** [comment]
Yep I agree, I reckon a medium-grey should get the job done.
