### ISSUE TITLE
Extracting koi crud config from the model

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#328]
- Start Date: 2017-04-04
- Owner: BP
- RFC PR:

# Summary

Koi crud config could be extracted from the model into a concern.

# Motivation

Our models sometimes get very large and messy, and often, a lot of it is just koi crud config. Some developers find this ugly / hard to work with. 

# Detailed design

Without changing the way anything in Koi works, Crud config could instead live in a concern. Example:

```ruby
# app/models/concerns/super_hero_config.rb
module SuperHeroConfig
  extend ActiveSupport::Concern

  Gender = ["Male", "Female", "Robot"]
  Powers = ["X-RAY VISION", "REGENERATION", "TOTAL RECALL", "TELEPORTATION",
            "WEATHER CONTROL", "FORCE FIELDS", "UNDERWATER BREATHING", "SUPER STRENGTH"]

  included do
    has_crud ajaxable: true,
             searchable: [:id, :name, :gender, :powers],
             orderable: false, settings: true,
             paginate: true

    setting :something_else, "This is another value", field_type: :rich_text, role: "Admin"
    setting :something, "This is a value", field_type: :text, role: "Admin"

    crud.config do
      fields image: { type: :image }
      config :admin do
        index fields: [:id, :name, :image, :file]
      end
    end

  end
end

# app/models/super_hero.rb
class SuperHero < ActiveRecord::Base
  include SuperHeroConfig
  # this file can now be just regular rails model stuff
end

```

If we decided we liked this pattern, we'd probably want to change the generators to create a config concern for the model, rather than embedding it in the model. 

# Drawbacks

- Pulling it into a separate file obfuscates it quite a bit
- constants that are used by the crud config need to live in the config concern (which might not be a bad thing?)
- personally I don't have a problem with crud config being in the model, as it makes it easier to find / search / modify it
- lines might get a bit blurry on occasion, as to whether a bit of code should live in the config concern or the model itself

# Alternatives

- We keep doing it how we've been doing it. We're comfortable with this.
- We look into what Matt was doing to rework the whole crud config. 

# Unresolved questions

It'd need pretty thorough testing to make sure this doesn't add limitations to the way we usually do things.

**Comment by dbaines** [comment]
> Pulling it into a separate file obfuscates it quite a bit 

I don't think that's too big of an issue. If someone is looking at `SuperHero.rb` for the Koi Config, they can see an `include SuperHeroConfig` and should be able to put two and two together. 

Since it is specifically for Koi, should we include Koi in the naming convention somehow? `SuperHeroKoiConfig` for example? Might get a bit unnecessarily verbose.

**Comment by Obversity** [comment]
> should we include Koi in the naming convention somehow? 

I'm in favour of keeping it as concise as possible. I don't see rails or any other gem we'd use bringing out a `<ModelName>Config` convention any time soon, so we're probably safe to use it ourselves.

**Comment by jsidoryn** [comment]
Could this be optional? For simple models it might be nice to have it right there but as things get more complex it might be nice to push it into a concern?

**Comment by Obversity** [comment]
> Could this be optional?

I mean, it's already optional. We're just opting into not doing it at all, at the moment. 😛 

But yes, I suppose we could make it optional in the generators somehow, maybe with a flag or something. I think that'd be more effort than it's worth though. Consistency is better than marginally improved simplicity, in the long run, in my opinion. As in, if we go ahead with this, I'd rather know that on new projects, I can *always* find crud config in the `<model_name>_config.rb` file, than have to check the model first and if it's not there, look for the config file.

**Comment by jsidoryn** [comment]
@Obversity that makes sense. as we're usually doing fuzzy search in our editors, only having one place to look will make it quicker. 

so is there any consensus on moving it out? @pvawser01 ?

**Comment by Obversity** [comment]
Just to be clear, I'm not necessarily pushing for moving it out. I'm undecided. I'm just raising it as a possibility. Maybe we could trial it on a greenfield project at some point, see how it feels.

**Comment by pvawser01** [comment]
@jsidoryn Moving it out to a model can have two benefits. I the admin config can be loaded at initialisation rather than each time a model is instanciated. Also, it keeps the domain logic seperated.

I'd be ok with it.

**Comment by Obversity** [comment]
> the admin config can be loaded at initialisation rather than each time a model is instanciated

What do you mean by 'initialisation' here? Crud config is currently loaded when the model is evaluated, not when a model is instantiated (e.g. `MyModel.new`). 

![image](https://cloud.githubusercontent.com/assets/7999019/24684566/27d7f8c4-19e6-11e7-9175-cbbed637fa9c.png)
