### ISSUE TITLE
Missing database.yml.example file

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#339]
- Start Date: 2017-06-28
- Owner: TBA

# Summary

It looks like at some point Koi has stopped generating `database.yml.example` files. It still generates a `database.yml` file but this doesn't get committed for obvious reasons. 

# Steps to reproduce

Pull down a recent project, eg. OPN. 

# Expected results

There should be a `database.yml.example` file, so the new developer can easily duplicate, plug their details in and be set up in seconds. 

# Actual results

There is no `database.yml.example` file. The new developer must know the required filename, file location and structure of the file to continue setting up the project. 

# Additional notes

I personally have a snippet in my editor to populate a `database.yml` for me so it's only a very minor annoyance for me. I expect this isn't the case with everyone though.

**Comment by Obversity** [comment]
Definitely worth fixing. 👍

**Comment by sobakasu** [comment]
generators have been removed from koi. 
you can use the rails new generator to generate a database.yml.
e.g. `rails new project_name --database=postgresql`
