### ISSUE TITLE
Issue / feature: select whether URL rewrite is permanent or temporary 

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#375]
Clients need url rewrites for a variety of purposes, and sometimes they need the redirect to be temporary and other times they need it to be permanent. 

Currently we're always doing a 301 redirect, which can get people's browsers into a state where it's impossible to visit their content after, say, creating a page to replace a redirect. 

UI wise, I'd propose either a checkbox saying "Permanent redirect", or a select box with both options, defaulting to "Temporary redirect". We may want some hint text explaining the difference to customers.

**Comment by sfnelson** [comment]
Fixed in latest version
