### ISSUE TITLE
Content component edit modal width 

### ISSUE THREAD

**Issue by jamiekatalyst** [katalyst/koi#609]
When the user browser is narrow the modal is too small. looks like it is percentage based rather than a minimum width.

**Comment by AlanCornthwaiteKatalyst** [comment]
Correct, it was using a percentage based width on desktop. Have created a PR in https://github.com/katalyst/kpop/pull/57 to change to use the same width as the mobile breakpoint as the width of the container. Doing this creates a smooth transition when going from desktop to mobile.
(as the container hits the left edge of the screen it converts to "mobile" view)

The mobile breakpoint for the side panel is 600px.

**Comment by sfnelson** [comment]
Fixed in latest kpop release
